### ISSUE TITLE
Accessing Docksal Docs while working offline

### ISSUE THREAD

**Issue by thejimbirch** [docksal/docksal#1027]
As a developer with no Wi-Fi, you can't access the docs on how to tell the localhost to not access the internet, making it impossible to work offline.

Naturally, I tried `fin help`, but that did not contain the help I was looking for.

Please consider adding some kind of help documents that could be accessed by the CLI or the upcoming UI while working offline.

**Comment by achekulaev** [comment]
Hi. 

>  docs on how to tell the localhost to not access the internet

I am not sure I understand which docs you are referring to.

Working with Wi-Fi turned off is generally pretty hard on *nix platforms in general (because DNS resolution will not work) and it is a **_very_** marginal case. 

Internet access is pretty essential nowadays, at the same time supporting a separate offline docs would be quote an effort, so I am not sure if efforts/benefits ratio is very high here.
