### ISSUE TITLE
Load custom .env file

### ISSUE THREAD

**Issue by Flower7C3** [docksal/docksal#1041]
**Description**

If I define `DOCKSAL_ENVIRONMENT=custom` in `docksal.env` file it will not cause loading `docksal-custom.env` file because declaration ([line 5816](https://github.com/docksal/docksal/blob/edbc6b073caf994bc7763cc45d375c0f9055035a/bin/fin#L5816) from `bin/fin` file):
```
local local_env_file="$(get_project_path_dc)/.docksal/docksal-${DOCKSAL_ENVIRONMENT}.env"
```
is before _if statement_ from lines [5817 to 5822](https://github.com/docksal/docksal/blob/edbc6b073caf994bc7763cc45d375c0f9055035a/bin/fin#L5817,L5822) from `bin/fin` file.

**Output of `fin config`:**
```
fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: example-php-app
COMPOSE_FILE:
/home/test/.docksal/stacks/overrides-osxfs.yml
/home/test/.docksal/stacks/volumes-bind.yml
/home/test/.docksal/stacks/stack-default-nodb.yml
/home/test/projects/example-php-app/.docksal/docksal.yml
/home/test/projects/example-php-app/.docksal/docksal-custom.yml
ENV_FILE:
/home/test/projects/example-php-app/.docksal/docksal.env
```

**Comment by lmakarov** [comment]
I'd say this is intentional - `DOCKSAL_ENVIRONMENT` should not be set in `docksal.env`.

The idea with `DOCKSAL_ENVIRONMENT` was to have it set in the host environment (e.g. CI) and have `fin` load the extra environment overrides (env and yml). So, you'd have `export DOCKSAL_ENVIRONMENT=ci` in CI to have the overrides in `docksal-ci.env`/`docksal-ci.yml` applied during the CI build (those files are expected to be committed to git).

By default, `DOCKSAL_ENVIRONMENT=local`, so you can have local overrides in `docksal-local.env`/`docksal-local.yml` (those are expected to be gitignored).

@Flower7C3 maybe you can explain your use case, so we can better understand the intents?

**Comment by Flower7C3** [comment]
@lmakarov it sounds good. I will use it in that way. It should be described also in documentation.

**Comment by lmakarov** [comment]
@Flower7C3 yep, added these details to the docs ^.
