### ISSUE TITLE
Allow containers other than `cli` to use bash by default

### ISSUE THREAD

**Issue by JDDoesDev** [docksal/docksal#1107]
**Description**

When trying to set up a docksal instance to simulate a decoupled site using different servers (Default stack with additional CLI for React/Node/Gatsby type) I noticed that in order to run commands like `fin exec --in=nodeapp yarn start` or `fin exec --in=nodeapp npm install` where `nodeapp` is the name of the service, I had to go through some significant hoops to get it to work.

**Steps to reproduce the issue:**

1. Add a second CLI based service to `docksal.yml`
2. Try to run a command in the service `fin exec --in=nodeapp npm install`

**Describe the results you received:**

`sh: 1: npm: not found`

**Describe the results you expected:**

Things to install

**Comment by JDDoesDev** [comment]
I have made a fix for this and submitted in PR #1108

**Comment by lmakarov** [comment]
@JDDoesDev thanks for submitting the issue and a PR to address it.

Looking at #1108, I'd approach this from a different angle - using container labels.

In `docksal.yml`

```
nodeapp
    ...
    labels:
      - io.docksal.shell=bash
    ...
```

To read the value of the label:

```
docker inspect --format '{{ index .Config.Labels "io.docksal.shell"}}' nodeapp
```

We should apply the same approach to all stock services defined in [services.yml](https://github.com/docksal/docksal/blob/develop/stacks/services.yml)

**Comment by achekulaev** [comment]
@lmakarov haha I commented the same in PR without seeing the ticket first! 😆

**Comment by lmakarov** [comment]
@achekulaev good to see we agree on the approach here ;)

**Comment by JDDoesDev** [comment]
Made some changes and added a new PR #1113.  Let me know if this works or what should be added/removed/blown up.  Cheers!

**Comment by achekulaev** [comment]
@JDDoesDev it would be too long to review your PR. Too many things needed to be changed. Setting shell was not enough. You also need to set user. 

Anyways I have created new PR for this. Closing your in favor of the one I created.

**Comment by wietsewarendorff** [comment]
Hi @achekulaev , just tested #1122 and it works perfectly when I add the labels to a new service.

Just a question: why not set these labels for cli in stacks/services.yml, so you can remove the if-statements (like this: `if [[ "$container_name" == "cli" ]]; then`) in the fin-script completely? This would make it even more configurable imho, because I can override it even for the cli-service (if I would like to).

**Comment by achekulaev** [comment]
@wietsewarendorff for backwards compatibility

**Comment by achekulaev** [comment]
@wietsewarendorff `if` statement for `cli` case will stay anyways to include the user. Other than that frankly I have not thought about allowing the shell override for canonical `cli`. And I am not sure if it is the best idea, as it can impact many other commands that rely on `fin exec` (like db commands) in a very opaque manner. Having `cli` service in your project is a very fundamental unspoken requirement of the Docksal project, and having it functioning properly seems inherently very important. Maybe once we officially support (e.g. "testing everything against") additional shells inside `cli`, then it might be changed.

**Comment by wietsewarendorff** [comment]
Hi @achekulaev thanks for your reply, very nice to see you are open for discussion. It was not my intent to change the settings for the cli container, I was looking for a way to clean the fin-script of non-needed code.

The added labels provide a nice, consistent way to setup all docksal containers. Adding these labels to the default services.yml file will make sure everything works just like it does now.
I don't see why there should be an exception for the cli-container. They current if-statements even prevent me from making custom changes to my cli-setup! Plus, if I want to change to name of the cli-container (or want to use 2 cli-containers) I now have to add the labels manually, and that should not be necessary.

I understand the fact that the cli-container is a requirement in almost all docksal projects, I guess I am looking for a way to drop any dependencies on the name `cli` in the fin-script.

**Comment by achekulaev** [comment]
> I don't see why there should be an exception for the cli-container

Imagine I am a `zsh` fan using Docksal. I want to use `zsh` everywhere! I want to use it in `cli` too (this is not a made up requirement, there are open issues like that). 
I learn about this label. I learn that `cli` has `zsh` pre-installed (or I use a custom Dockerfile to install it). And I override the shell. Everything works great! Until 2 months later I find out that `fin db truncate` stopped working. I go and raise a ticket because it's not working with a weird error. 

As a Docksal maintainer I would not even remotely be happy to debug the issue with so many variables to understand whether I need to fix some edge case on some OS or configuration, or whether it's not my issue at all.

> They current if-statements even prevent me from making custom changes to my cli-setup!

Not sure what you mean by this. Current if statements do not prevent you from customizing your `cli`, they just slightly limit the ways you can do it.

> I want to change to name of the cli-container (or want to use 2 cli-containers) I now have to add the labels manually, and that should not be necessary.

This is a good point. I will add this label to the `cli` container definition, so you could extend on it, but that case with `zsh` I explained above should demonstrate why I am still not convinced regarding removing the special clause for a service named `cli`.
