### ISSUE TITLE
[ErrorException] rename(/usr/local/bin/composer): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by AlexShapka** [docksal/docksal#1126]
**Description**

Wanted to give a try to [Drupal Module Upgrade](https://www.drupal.org/project/drupalmoduleupgrader) module, however according to https://www.drupal.org/project/drupalmoduleupgrader/issues/3072073

`Composer version 1.8.0 2018-12-03 10:31:16`

is not new enough. Attempting to update it is giving:

```
fin composer self-update
Updating to version 1.9.0 (stable channel).
   Downloading (100%)         

                                                                             
  [ErrorException]                                                           
  rename(/usr/local/bin/composer): failed to open stream: Permission denied  
```

What is the right way to update composer in docksal?

**Comment by lpeabody** [comment]
If you run `fin bash` and then in the container run `sudo -s` that will let you run `composer selfupdate` successfully. However, do realize that this would be undone if you reset/recreated the container.

**Comment by AlexShapka** [comment]
lpeabody, it worked like a charm. Thanks lot! Do you think I could indicate composer version somewhere in container configuration files, so it is created with the most updated composer?

**Comment by lpeabody** [comment]
@AlexShapka in order to get the updated Composer version to be a permanent change within the context of your project, you would need to extend the cli image that the project is using and have it install the latest version of Composer. You can follow the example in the documentation here https://docs.docksal.io/stack/extend-images/.

Assuming you're using Docksal's docksal/cli:2.6-php7.2 image, it might look something like this:

.docksal/services/cli/Dockerfile:
```
FROM docksal/cli:2.6-php7.2

ENV COMPOSER_VERISON=1.9.0

RUN set -xe; \
	# Composer
	curl -fsSL "https://github.com/composer/composer/releases/download/${COMPOSER_VERSION}/composer.phar" -o /usr/local/bin/composer
```

And [update your docksal.yml](https://docs.docksal.io/stack/extend-images/#extend-docksal.yml) file (in addition to whatever else you have in there already) to reference the above:
```
version: "2.1"

services:
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: services/cli
```

Then you should run `fin reset cli`. That will tell Docksal, who will tell Docker, to build the new cli image that is specific to your project and use that image when creating your project's cli container.

Hope this helps.

**Comment by shelane** [comment]
The composer version, along with several dev tools will be updated in the next release.

**Comment by lmakarov** [comment]
Corresponding PR: https://github.com/docksal/service-cli/pull/132
