### ISSUE TITLE
Docksal with VB Proper creation of virtual machine has failed

### ISSUE THREAD

**Issue by jernejbeg** [docksal/docksal#1156]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
I am using Docksal with VirtualBox on MacOS and I have encountered a problem on some networks. 

If I use Docksal at home or via a hotspot everything works fine, but if I try to run fin system start at work it fails. I guess that the IP address of the VM is already in use, but I can't figure out how to change it. 

**Steps to reproduce the issue:**
1. Try it on a corporate network or on a network where the 

**Describe the results you received:**
I get the following in the terminal: 
Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: host-only cidr conflicts with the network address of a host interface

ERROR:  Proper creation of virtual machine has failed

**Describe the results you expected:**
1. That docksal starts working

**Comment by achekulaev** [comment]
It is not really an easy task to change IP of the machine. 

There re 3 variables that control it but I believe at this point is might also be hardcoded in some other images.

I would recommend using Docker Desktop on work as a fallback. Along with using NFS volumes it does not have any performance problems (https://docs.docksal.io/core/volumes/#using-nfs-volumes). NFS volumes is going to be the default option in the upcoming release.

If you updated to Catalina though to use NFS volumes you would need to some steps (because Apple decided to change so much about FS) or wait until the upcoming release where Catalina is going to be fully supported.
