### ISSUE TITLE
"Waiting for project stack to become ready..." timeout

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#1157]
Sometimes we have this within CI:

![image](https://user-images.githubusercontent.com/10816446/66191286-a937cc80-e696-11e9-9d21-f07aadf089f5.png)

How to increase this timeout?

**Comment by ey-** [comment]
This is currently hardcoded:
https://github.com/docksal/docksal/blob/develop/bin/fin#L1432

**Comment by lmakarov** [comment]
@ArtuGit it is no normal for a project stack to take longer than 60s to start. Try looking at the logs (`fin logs`) to see what's going on.

**Comment by lmakarov** [comment]
> we experience that also sometimes in our CI. It is mainly the case when multiple builds are running in parallel and there is not enough CPU resources available for the containers to start

@ey- that makes sense.

While it's a trivial thing to make this timeout configurable, increasing it will not solve the root cause, only bury it deeper. It will be very helpful to understand which of the containers fail to satisfy the healthcheck and look if there's anything that can be improved there.
