### ISSUE TITLE
Virtual hostname duplication?

### ISSUE THREAD

**Issue by ComboPrime** [docksal/docksal#116]
A week ago I was able to run a D7 site and a D8 site simultaneously with no problems. I don't know what changed, but for the past 5 days I've been unable to start the D7 site. I keep getting this error:

 ERROR:  Can not start another project with the virtual hostname 'etglocal.docksal'
         Use a different hostname for this project. Run fin projects -a to list all projects.

fin projects -a shows only one project with that virtual hostname, and it's not running:

```
PROJECT             STATUS                  VIRTUAL HOST        PROJECT ROOT
etg8                Up 4 minutes            etg8.docksal        /Users/xxx/Sites/etg8
etglocal            Exited (0) 5 days ago   etglocal.docksal    /Users/xxx/sites/etglocal
```

So I don't know why fin means by "another project" with the same virtual hostname. i've already tried destroying the docker machine and re-creating both projects, no luck.

Thanks for your help!

**Comment by achekulaev** [comment]
Hi @ComboPrime 

Thanks for reporting back problems. 

As far as I see in the output of your `fin projects -a` you already have a project with `VIRTUAL_HOST` column showing `etglocal.docksal` located in `/Users/xxx/sites/etglocal` folder. (BTW [this is how](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) to format text as code on GitHub)

```
PROJECT             STATUS                  VIRTUAL HOST        PROJECT ROOT
etg8                Up 4 minutes            etg8.docksal        /Users/xxx/Sites/etg8
etglocal            Exited (0) 5 days ago   etglocal.docksal    /Users/xxx/sites/etglocal
```

So despite `etglocal` it's not running, trying to run **another** project in **another** folder with the same `VIRTUAL_HOST` value can lead to problems, that's why fin prevents it. 

You need either to remove the old project containers by running `fin rm` in that `/Users/xxx/sites/etglocal` or change `VIRTUL_HOST` value for the project you're trying to launch.

By default, if you don't specify `VIRTUAL_HOST` manually then fin uses project folder name as `VIRTUAL_HOST`.
e.g.  
`/Users/alexei.chekulaev/Projects/demo` would have `demo.docksal` as `VIRTUAL_HOST`  
`/Users/alexei.chekulaev/Projects/another project 2016` would have `anotherproject2016.docksal` as `VIRTUAL_HOST`
You can find current `VIRTUAL_HOST` value in the output of `fin config` for your project.

You can override that behavior it in `docksal.env`, be sure to use `.docksal` domain.

```bash
VIRTUAL_HOST="delibiratehostname.docksal"
```

After you make sure your new project `VIRTUAL_HOST` does not conflict with any of existing projects you should be able to run it.
Hope this helps!

**Comment by achekulaev** [comment]
Hi @ComboPrime 

Thanks for reporting this. There is a bug. Meanwhile rename a folder of your another project to be something else rather than etglocal and you should be able to start it.

**Comment by achekulaev** [comment]
Try renaming it to `_etglocal` for now

**Comment by ComboPrime** [comment]
Thanks for the fast response!

I tried renaming “etglocal” to “etg7” but still get the same error (presumably because docksal.env specifies “etglocal.docksal” as the VIRTUAL_HOST).

Changing VIRTUAL_HOST in docksal.env gets the project running again, although fin projects -a still shows an “etglocal” project:

PROJECT             STATUS                  VIRTUAL HOST        PROJECT ROOT
etg7                Up 24 seconds           etg7.docksal        /Users/elliot/sites/etg7
etg8                Up 12 hours             etg8.docksal        /Users/elliot/Sites/etg8
etglocal            Exited (0) 5 days ago   etglocal.docksal    /Users/elliot/sites/etglocal


…not sure how to get rid of that.


etg

**Comment by achekulaev** [comment]
> fin projects -a still shows an “etglocal” project:

You might have orphaned containers. `fin cleanup` should help.

**Comment by ComboPrime** [comment]
That did it! Thanks again—

etg
