### ISSUE TITLE
Question: exclude folder from being mounted

### ISSUE THREAD

**Issue by stenvdb** [docksal/docksal#1180]
Quite new to docksal, so still figuring things out.

I'm finding out that sharing _a lot_ of folders between the host and a container becomes _very_ slow and cpu heavy (at least on a mac with docker for mac). After doing some research, I've read that making sure composer vendor folders only live _inside_ your container, and not on your host, results in a major performance boost.

Can someone help me with how I might achieve that? So either a way to exclude a folder from being mounted, or a way to mount only a select group of folders. Haven't got it working so far.

**Comment by achekulaev** [comment]
There is no technical way to exclude files from sharing. I cannot think of any network file system where you can exclude files. 

If you want certain files not to be shared you would have to create them outside of the shared root. I.e. if you want files to exist in container only you can create them outside of `/var/www`.

Alternatively you can avoid syncing files with container at all. You can use `DOCKSAL_VOLUMES=none` (see https://docs.docksal.io/core/volumes/#none-volumes) and in this case container FS will not be connected to host FS. You would need to use `fin bash` and checkout files with git from inside of the container and then use it to commit them there too. Or you could use [docker cp](https://docs.docker.com/engine/reference/commandline/cp/) to copy files once into container and then continue working there. Just remember you would need a way to save you changes anyways (i.e. git or other version control system).

---

P.S. Theoretically you could use `DOCKSAL_VOLUMES=unison` (https://docs.docksal.io/core/volumes/#using-unison-volumes) and then add proper value to `SYNC_EXTRA_UNISON_PROFILE_OPTS` to ignore what you need, but this is really advanced case with a lot of consequences one must understand, so I would not recommend it for a new user.

**Comment by lpeabody** [comment]
You could potentially also utilize Composer's ability to specify a different vendor directory other than the default project level `vendor` directory (https://stackoverflow.com/questions/11883374/how-to-specify-composer-install-path). So like @achekulaev said, you could specify it be outside of the project root (like, /var/vendor maybe). The only thing you'd have to do is make sure that whatever you're using for an autoloader knows where the vendor directory is. Also, if you did this, you would likely lose any IDE code completion help since your IDE would not be able to scan the vendor directory in the project.

**Comment by stenvdb** [comment]
@lpeabody Thanks, that's definitely an option here. It's basicly what's being described [here](http://blog.michaelperrin.fr/2017/04/14/docker-for-mac-on-a-symfony-app/), correct?

@achekulaev Thanks for clarifying that that's not possible 🙂 Maybe there is another approach though.. I was looking at [this article](https://mattgrayisok.com/a-craft-cms-development-workflow-with-docker-part-1-local-development) (see the part that begins with "_In docker-compose.yml update the nginx and php volumes to:_"). Is there a way I don't mount my entire project root folder to `/var/www`, but instead specify which folders inside my project root I want to mount?

**Comment by achekulaev** [comment]
@stenvdb you can alter volumes definition and mount only what you need, however you would lose a lot of goodness. Docksal has different volumes definitions for different OS, so that your configuration worked if colleague from another OS uses it. This is what was lacking in Docker Compose and where Docksal project started to begin with. If you alter volumes definition you'd lose that.

**Comment by stenvdb** [comment]
Thanks both for the feedback! I won't go that route then 👍  (though still considering installing vendor in `/var/vendor` or something like that)

What got me doing some research on this is my CPU going overboard. I recently did a clean install of docksal and docker for mac to play around with. But running a (not _that_ big even) `composer install` inside a fresh container, results in my CPU hitting 300% and more, fans spinning up loudly. Do you have any tips/experience on this?

**Comment by achekulaev** [comment]
@stenvdb yes I have a tip "don't use composer" :) You should have explained the nature of the issue from the beginning. There is no way around that. It's not so much about the shared filesystem as it is about the composer itself and Docker filesystem. You gonna save like maybe 50% out of those 300% if you move files outside of `/var/www` but it is not going to be a dramatic change. It's just a composer and Docker tax. Running the same on host will probably be like 150%.
Also you could limit amount of CPUs available to Docker. If you make it 2, then CPU usage will never exceed 200% but you fans will still spin when composer runs.
