### ISSUE TITLE
Document using unison volumes

### ISSUE THREAD

**Issue by christianwiedemann** [docksal/docksal#119]
Hi,
I am very interested in using docksal with nativ docker on mac and unison. I hope this could be a fast configuration for a large drupal 8 project. I saw unison volume configuration. Would you suggest such a configuration? Can you Provide documentation for unison?

thanks!
Christian

**Comment by lmakarov** [comment]
@christianwiedemann I would not recommend using Docker for Mac. It used to be terribly slow out of the box (due to the osxfs file system performance issues), however recent versions went even further and introduced more performance issues even when using native/container file system (e.g. when syncing files with unison). See https://github.com/docker/for-mac/issues/668

If you'd like to try it yourself:

1. Follow the instructions [here](http://docksal.readthedocs.io/en/master/getting-started/env-setup-native/) to properly configure Docksal for use with Docker for Mac. Make sure you have the most recent fin version installed.
3. Run `fin create-site` and setup a sample Drupal 8 project. Name the project `drupal8-test`. This will download the sample project repo and run `fin init` (initialize Drupal settings, stack and install the site).
4. Now add `DOCKSAL_VOLUMES=unison` in `.docksal/docksal.env` in the project
4. Run `fin reset`. Wait until the `osxfs` process on you Mac "cools down" - that's how you know unison is done with the initial sync.
5. `cd docroot && fin drush si -y`
6. The site will be available at http://drupal8-test.docksal (which should resolve to `127.0.0.1` when using Docker for Mac)

Currently there is no good way to know when unison is done with the initial file sync. This makes it not possible to script the project provisioning process with `fin init` (the script will proceed with site install/etc. steps before the code base is ready).

And here is a performance comparison I run from time to time (measuring time to install a vanilla Drupal 8 site via Drush) to see how Docker for Mac is doing compared to Docksal setup using boot2docker and NFS.

![image](https://cloud.githubusercontent.com/assets/1205005/23809624/3fb4f126-0583-11e7-87eb-8dea37a5efb6.png)
(Lower values are better)

**Comment by EugenMayer** [comment]
Probably have a look at http://docker-sync.io - with the new usage of native_osx you get native performance on shares, while not beeing in need to run unison/unox on OSX ( CPU heavy task )

**Comment by lmakarov** [comment]
https://docs.docksal.io/en/develop/advanced/volumes/

**Comment by apredmore-tag** [comment]
Page was moved: https://docs.docksal.io/core/volumes/
