### ISSUE TITLE
Issues with NFS on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1296]
Reported in https://gitter.im/docksal/community-support by @rfay

> I'm trying to install Docksal on a clean macOS Catalina, have tried on two different machines. No matter what I do I get some permutation of ERROR: NFS sharing has failed. For example, with an empty /etc/exports, I get:
> 
> ```
> $ fin system reset
> Configuring network settings...
> Configuring NFS shares...
>  ERROR:  There is an error in /etc/exports file
>         Read through the error message(s) below and fix errors in /etc/exports manually
>         Then run fin system reset
> -----------------
> ---> Got line: # <ds-nfs docksal
> ---> Got line: /System/Volumes/Data/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
> /System/Volumes/Data using UUID CBD1C659-0D22-4494-BEA6-43958CDA4391
> kernel export registered for /System/Volumes/Data/Users
> ---> Got line: # ds-nfs>
> -----------------
>  ERROR:  NFS sharing has failed
> ```
> 
> After this, /etc/exports is still empty.
> 
> I've granted full disk access to iTerm where I'm running it...

**Comment by achekulaev** [comment]
Interesting. Looks like there's some NFS export controlled by kernel for `/System/Volumes/Data/Users` already, if I ar reading it right

**Comment by rfay** [comment]
On my regular mac (which is often used with ddev, which also uses NFS) I did this:

```
sudo nfsd stop
sudo rm /etc/exports
```
then
```
$ fin system reset
Configuring network settings...
Configuring NFS shares...
 ERROR:  There is an error in /etc/exports file
        Read through the error message(s) below and fix errors in /etc/exports manually
        Then run fin system reset
-----------------
---> Got line: # <ds-nfs docksal
---> Got line: /Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
/System/Volumes/Data using UUID CBD1C659-0D22-4494-BEA6-43958CDA4391
kernel export registered for /System/Volumes/Data/Users
---> Got line: # ds-nfs>
-----------------
 ERROR:  NFS sharing has failed
```

At this point no /etc/exports exists. 

So yes, I would expect that this is interplay with existing nfs shares... but certainly not current shares, since /etc/exports is gone and nfsd is gone. 

So at the very least the error message

>  ERROR:  There is an error in /etc/exports file
>        Read through the error message(s) below and fix errors in /etc/exports manually
 >       Then run fin system reset

is both incorrect and also not helpful in any way.

**Comment by rfay** [comment]
On a different macOS 10.15.3 machine I got `fin system reset` working by 
`sudo rm -f /var/db/mountdexptab /etc/exports && sudo nfsd stop`, but I haven't been able to do that here on this one. 

I note that the error message says
```
Got line: /Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
/System/Volumes/Data using UUID CBD1C659-0D22-4494-BEA6-43958CDA4391
```
and I note that on macOS Catalina (as every user of NFS on Catalina discovered) the line would be something like `/System/Volumes/Data/Users ...` because /Users can't be shared any more. But I sure don't know where it's coming up with that line, with no /etc/exports and the /var/db/mountdexptab gone.

**Comment by achekulaev** [comment]
On your regular mac the fin must be older, the one which doesn't know about Catalina

**Comment by rfay** [comment]
```
fin --version
fin version: 1.93.0
```

**Comment by laurelstreng** [comment]
I'm also having issues with NFS on macOS Catalina 10.15.3, but mine may differ from @lmakarov 's initial issue. I can open up a separate ticket if necessary.

When running `fin system start` I'm running into NFS mount errors and I have no idea what is going on:
```
[lstreng] [relias]$ fin system reset
Configuring network settings...
Configuring NFS shares...
Writing /etc/exports...
Restarting nfsd...
Mounting NFS shares...
Mounting local /Users/lstreng/Projects to /Users/lstreng/Projects
mount.nfs: requested NFS version or transport protocol is not supported
exit status 32
Retrying mounting local /Users/lstreng/Projects to /Users/lstreng/Projects
mount.nfs: requested NFS version or transport protocol is not supported
exit status 32
 ERROR:  NFS share mount failed.
        Try fin vm mount or fin vm restart.
Resetting Docksal system services...
 * proxy
 * dns
   upstream 1.1.1.1
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
```

**Comment by gonzamace** [comment]
I got Mac given from my Company, I´m a separete User from the original who setup the Mac and of course I don't have access to a variety Mac settings. 
But let me clarify that the Firewall settings are correctly set to raise environments with Docker.

**Using bind or unison start the project normally. But not with nfs**

System info:
macOS Catalina v10.15.4
Docker v2.3.0.2 (Engine 19.03.8)
Docksal v1.13.3
Fin v1.95.0

I´ve tried on local as global docksal.env:

DOCKSAL_VOLUMES="nfs"
DOCKSAL_NFS_PATH=/Users/rodriguez/Documents/Sites/university

And this is the Output:

Starting services...
Creating network "university_default" with the default driver
Creating volume "university_cli_home" with default driver
Creating volume "university_project_root" with local driver
Creating volume "university_db_data" with default driver
Creating university_db_1 ... done
Creating university_cli_1 ... error
Creating university_pma_1 ... done

ERROR: for university_cli_1 Cannot start service cli: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused "rootfs_linux.go:58: mounting \"/var/lib/docker/volumes/university_project_root/_data\" to rootfs \"/var/lib/docker/overlay2/26c08186a67947c50fb6257ae1a96b9f10889e24686d810ef67f81cbb9c8fe28/merged\" at \"/var/www\" caused \"stat /var/lib/docker/volumes/university_project_root/_data: stale NFS file handle\""": unknown

ERROR: for cli Cannot start service cli: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused "rootfs_linux.go:58: mounting \"/var/lib/docker/volumes/university_project_root/_data\" to rootfs \"/var/lib/docker/overlay2/26c08186a67947c50fb6257ae1a96b9f10889e24686d810ef67f81cbb9c8fe28/merged\" at \"/var/www\" caused \"stat /var/lib/docker/volumes/university_project_root/_data: stale NFS file handle\""": unknown
ERROR: Encountered errors while bringing up the project.

@achekulaev if you think this issue is not related I can open a new ticket.

**Comment by lmakarov** [comment]
Closing for now as there have been no new reports of this issue. Also, with recent macOS Catalina versions (10.15.4+) `/Users` can be used as before for NFS exports instead of `/System/Volumes/Data/Users`.

**Comment by rfay** [comment]
I had no idea they made /Users work with NFS again. Thanks for that update.
