### ISSUE TITLE
Recommended: Docker for Mac, VBox for Windows

### ISSUE THREAD

**Issue by macmladen** [docksal/docksal#1312]
I know this may be repeated question, but things do change and we all need to lessen the burden on our machines, be it venerable 2011 MacBook Pro with 8GB or latest 16" with 32GB.

So aside for requirements (like Vagrant et al) what is the best course to be taken to deploy **fin** based workflow for average Drupal/WordPress developer who just seeks to deploy and manage project easily and have them performed well?

For **Mac** is _Docker for Mac_ preferable to VirtualBox and why? Which has better performance in terms like the site responsiveness? (Mac uses native _Hypervisor_ for Docker, too: https://docs.docker.com/docker-for-mac/docker-toolbox/)

For **Windows** is the _Vagrant_ option the only downside of using _Docker for Windows_?

On the site at the moment, **Docker for Mac** is recommended and **VirtualBox** for Windows.

Does that still hold and can you give us some background why?

Thanks 🙂

**Comment by achekulaev** [comment]
Docker Desktop and VBox have similar performance on Mac so I use DD, because it has more convenient UI that Vbox. Neither is "better" than another in term of their purpose.

On Windows everything is the save. If you run DD then you can't run other virtualizations, VBox/VnWare/whatever. But hopefully we should be able to switch to WSL2 this year by using Docker inside WSL2.
