### ISSUE TITLE
Handle /etc/exports conflicts on macOS

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#133]
Docker VM and some other software will conflict with Docksal on macOS over `/etc/exports` file.

To give users ability to use them next to each other:
1. During Docksal VM start comment out conflicting exports
2. In case there are conflicting exports, during Docksal VM stop comment out Docksal exports and uncomment conflicting ones.

Thus user will be able to use Docksal by starting Docksal VM. And switch back to another software by stopping Docksal VM.

**Comment by lmakarov** [comment]
As an alternative approach we can narrow down the scope of the NFS export from `/Users` to a specific folder (e.g. `/Users/<username>/docksal-projects`), where all Docksal powered projects will reside.

**Comment by Decipher** [comment]
It would be ideal to narrow down the scope, as I actively work on both Vagrant (Beetbox) an Docker (Docksal) based projects concurrently. It would also be ideal to just use the paths that the specific projects are in rather than trying to specify that a user use a specific location.

I understand that there is also the matter of the SSH keys, but would not a pre-packaged insecure key in `~/.docksal` satisfy?

**Comment by achekulaev** [comment]
You can put your Vagrant projects outside of your home folder as a workaround for now @Decipher

**Comment by Decipher** [comment]
@achekulaev The problem is that the whole team on many of those Vagrant sites (e.g., clients) have a practice of keeping those projects in a similar location so that anyone jumping in to debug issues would know how the site is set up. I don't doubt it would be easy enough to work around, but we shouldn't have to work around this issue, we should try to work to fix it.

**Comment by achekulaev** [comment]
@Decipher an the moment there is no way to use Vagrant along with Docksal if you keep both of them in home directory.

**Comment by lmakarov** [comment]
I'm actually not opposed to per project NFS exports, however the single folder approach sounds more straightforward.

Before we do that, however, we will have to refactor the way `fin ssh-add` works as it currently relies on being able to access the host user's SSH keys to load them in `docksal-ssh-agent`. Here's a feature requests for that - https://github.com/docksal/docksal/issues/223

**Comment by lmakarov** [comment]
After discussing this many times with @achekulaev we decided to go with the following approach:

- There will be a way to override the Docksal projects directory path (the NFS export path) via the global `~/.docksal/docksal.env`.
- The variable name will be `DOCKSAL_NFS_PATH`.
- By default we will continue to use `/Users`. This will make sure we do not introduce a breaking change for the exiting users.
- During `fin vm start`, if there is a conflict with the NFS exports configuration, an error will be thrown (this already happens) with short details about solving the problem and a link to the more detailed docs about the problem. `fin` will terminate the execution after this.
- The message will tell the user how to override the default NFS export path (set the `DOCKSAL_NFS_PATH` variable in `~/.docksal/docksal.env`, then restart the vm with `fin vm restart`) and offer setting it to `/Users/<user_name>/Projects` as a quick option.
- The docs will explain why this happens (e.g. conflicts with the existing Vagrant VMs on the host) and reiterate on the solution in more details.
- Since most of `fin` commands should be executed within the mount point (confirm this is really the case), we need to add a check for this on every `fin` invocation.
