### ISSUE TITLE
How to use libs like jpegoptim, optipng etc

### ISSUE THREAD

**Issue by stenvdb** [docksal/docksal#1357]
Coming from a MAMP environment, I've always been able to just link to a local binary (`usr/local/Cellar/jpegoptim/...`). Of course, that's not possible with docksal. Are these packages already installed (can't find any info in the docs) or what is the preferred way to install them. Preferably somwehere global as I don't want to install them for each new project.

**Comment by lmakarov** [comment]
Extra libraries and packages have to be installed inside the `cli` container. Since Docksal stacks are project specific, this has to be done per project. We have docs on how to automated the process so you would only have to do this once. See: https://docs.docksal.io/stack/extend-images/

Quick example (`fin bash`, then run commands below):

```
docker@cli:/var/www$ sudo apt-get update
....
docker@cli:/var/www$ sudo apt-get install jpegoptim optipng
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  jpegoptim optipng
0 upgraded, 2 newly installed, 0 to remove and 81 not upgraded.
Need to get 104 kB of archives.
After this operation, 251 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 jpegoptim amd64 1.4.6-1 [19.6 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 optipng amd64 0.7.7-1 [84.5 kB]
Fetched 104 kB in 0s (1,471 kB/s) 
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package jpegoptim.
(Reading database ... 20922 files and directories currently installed.)
Preparing to unpack .../jpegoptim_1.4.6-1_amd64.deb ...
Unpacking jpegoptim (1.4.6-1) ...
Selecting previously unselected package optipng.
Preparing to unpack .../optipng_0.7.7-1_amd64.deb ...
Unpacking optipng (0.7.7-1) ...
Setting up jpegoptim (1.4.6-1) ...
Setting up optipng (0.7.7-1) ...
```

I would recommend the [Dockerfile option](https://docs.docksal.io/stack/extend-images/#docker-file) from the docs.

**Comment by stenvdb** [comment]
Yes, thanks @achekulaev & @lmakarov, this is exactly what I needed 👍
