### ISSUE TITLE
Default ssh keys are not loaded into the ssh-agent on Ubuntu

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#180]
**Description**

When installing Docksal via `curl -L get.docksal.io | sh` on a fresh Ubuntu 16.04 they default ssh keys are not loaded into the ssh-agent service at the end of the installation.

**Steps to reproduce the issue:**

1. Clean Ubuntu 16.04
2. Generate an ssh key - `ssh-keygen`
2. Install Docksal - `curl -L get.docksal.io | sh`
3. Check ssh identities available in the ssh-agent service - `fin ssh-add -L`

**Describe the results you received:**

http://take.ms/BAj2y

```
leonid@ubuntu-vm:~$ fin ssh-add -L
The agent has no identities.
```

**Describe the results you expected:**

When system services are installed/reset the default keys should be added automatically:

```
Resetting Docksal services...
 * proxy
 * dns and resolver for .docksal domain
 * ssh-agent
Identity added: id_rsa (id_rsa)
```

**Comment by achekulaev** [comment]
On Linux keys are added upon project start.

**Comment by lmakarov** [comment]
I'm using docksal/drupal8 for testing and running `fin init`

There is a condition in the init script that does `fin reset -f` vs `fin up`.
https://github.com/docksal/drupal8/blob/master/.docksal/commands/init#L103-L109

So in case the host is already running (`DOCKER_RUNNING=true`), the script does `fin reset`.

I'm not sure if the init script should be adjusted or if we simply should add ad `ssh_add` call upon `reset` as well.

**Comment by achekulaev** [comment]
Yes we should add it to `reset`

**Comment by achekulaev** [comment]
I'm going to fix it by adding ssh-add to `reset` but not sure if it's the best decision to perform `ssh-add` during containers start/reset on Linux. 
1. I do not show any messages there. No "Importing ssh keys..." message. So password prompt can actually be confusing. Because user will not understand which password he is asked for.
2. It can be annoying if someone has password protected `id_dsa` or `id_rsa` and every `fin up` he's been asked for it

We might need to re-think it later.
