### ISSUE TITLE
The right way for managing tools like Composer, Drush, Drupal Console, NPM/NodeJS...?

### ISSUE THREAD

**Issue by ilakic** [docksal/docksal#194]
I have a couple of questions about Docksal so this is not a classical issue/problem.

I would like to know if there are already installed NPM and NodeJS in Docksal/Docker containers? If they are not, can I install them in a normal way like I would install them on non-virtualized Linux machine or I need to install new docker container(s) for that new tool (NPM, NodeJS)? 

Also, when working with Gulp, do I need to **$ fin bash** and then run Gulp (and install new NPM packages)? 
The same question is for Composer - do I need to run it within **$ fin bash** or I have to run that with Composer which is installed locally on the machine? (Of course that applies for PHP packages which are needed for work and for which you need to use Composer and also for Drupal modules.)

How can I upgrade Drush, Drupal Console and Composer?

Is there a way to add phpMyAdmin (at least as an option)?

By the way, I'm using Linux (Ubuntu 16.04) for development... 
I read official documentation but haven't found answers to my questions there... There is something about Sass and Compas but I'm not using Ruby Sass anymore (libSass is the way to go) so that's not relevant for my use case.

Thanks in advance!

P.S. And I have to say that this Docksal project is **_super-awesome_** - you guys **ROCK**! :)

**Comment by achekulaev** [comment]
Hi. Yes npm and node are pre-installed in `cli` container. 

```
$ fin exec npm -v
4.4.4

$ fin exec node -v
v6.10.0
```

You don't **have** to use Gulp from inside cli, and you can use your local tools, but recommended way to ensure the whole team uses the same version of a tool is to run it inside cli. It is also important to remember in case when you automate something. For example the most automated thing is initialization of a project after it's checkout from the repo. Usually people create a custom command named `init` where they automate settings, database import, scss compilation etc. And if you have a distributed team you would want it to run reliably everywhere. That's why you'd want to automate these actions using `fin exec gulp ...` rather that just `gulp ...` as the latter one would use whatever version is installed (or not installed!) on local host of another team member. Environment consistency is one advantages of Docksal. 

So either open `fin bash` and execute gulp from there or `cd` to the needed dir and run `fin exec gulp ...` there.

Same applies to composer, drush, drupal console.

Yes you can install additional npm packages inside `cli` as well as you can install additional software with `apt-get` as `cli` is based on Debian. And you can automate additional tools installation with custom commands like having an `init` command that performs `npm install` and the `gulp build`. Installed tools and packages won't go anywhere unless you delete or re-create `cli` container (which happens if you change an image used or perform `fin reset`)

Yes there is a way to use phpmyadmin, we are going to document it a bit later. In the meantime you can [expose a port](http://docksal.readthedocs.io/en/master/advanced/db-access/) of your `db` container and use any other DB management tool. Even another copy of local phpmyadmin.

**Comment by ilakic** [comment]
Thanks for fast & extensive reply Alexei! :100: 

Only the part about automation of additional tools isn't 100% clear to me... If I make a custom command like `init` for additional tools, will that custom command conflict with default one `init` command (I presume that you gave just an example when you said `init`)? 
Adding new commands looks like an easy task and I like that! Simple bash script and you have a new command. :+1: 

And if I add some new/additional Linux packages into the build what is the best way of sharing that with others in the dev group (team members)?

**Comment by achekulaev** [comment]
There is no default `init` command. All files under `.docksal/commands` are project specific custom scripts and are not default part of Docksal stack. You see them in projects like https://github.com/docksal/drupal7-advanced because those projects serve as examples on how to build and use those files. 

You're supposed to customize see that example and customize `init` to your needs (like adding tools installations there) or even create remove `init` that we provide and create your own from scratch if you'd like to initialize your project in a different way (for example often I just import database stored in git LFS in the `init` script instead of doing drush site install).

**Comment by achekulaev** [comment]
> if I add some new/additional Linux packages into the build what is the best way of sharing that with others in the dev group

The best way is to automate those packages installation in your `init` script and have the team to use `fin init` to initialize their site.

**Comment by ilakic** [comment]
Ok, that answers all my questions for now. 

Thanks once again!
