### ISSUE TITLE
Remove dependency on Virtualbox

### ISSUE THREAD

**Issue by mccrodp** [docksal/docksal#21]
Virtualbox is no longer needed on Mac, so is this still necessary as a requirement? https://github.com/docksal/docksal/blob/develop/docs/system-requirements.md

i.e. - using "Docker for Mac" (no Virtualbox required) https://docs.docker.com/engine/installation/mac/

> Docker for Mac is our newest offering for the Mac. It runs as a native Mac application and uses xhyve to virtualize the Docker Engine environment and Linux kernel-specific features for the Docker daemon.

I tried using this with Docker for Mac but got the error: 

> ERROR:  Required Virtual Box version is 5.1.2 or higher

Is it possible to re-write the customisations to use `xhyve` instead? I see it may only be the `fin` tools that require Virtualbox.

Why do the `fin` tools bundle their own `docker`, `docker-machine` and `docker-compose` versions / scripts in the `/bin` directory. I presume this overrides my installed scripts then.

I'd like to use and contribute to this repo, but am I downgrading to using Docker Toolbox / fin's custom scripts together with Virtualbox? In the meantime I'll use my [simple Docker Compose solution for Drupal](https://github.com/mccrodp/drupal-docker-compose).

**Comment by lmakarov** [comment]
> Virtualbox is no longer needed on Mac, so is this still necessary as a requirement?
Docker for Mac with osxfs is still very slow. Slower than VirtualBox with vboxsf.
NFS is still the most performant option if your workflow involves accessing code from the host (Mac).

Here's a simple test I'm using to compare performance: `time drush si -y`
Below a results with Drupal 7

VirtualBox (container fs, vboxsf, nfs): http://take.ms/r6YJJ
Docker for Mac (container fs, osxfs): http://take.ms/I5M3o

We have experimental support for Docker for Mac/Windows. It can be enabled via `export DOCKER_NATIVE=1` in a console session. This will disable checks for VirtualBox/etc.

> Why do the fin tools bundle their own ...
Docker cli and docker daemon have very narrow compatibility. It would usually break within 1-3 minor releases (whenever they change the REST API version). We do not want to rely on stuff users may have installed globally on their system and also do not want to rewrite that stuff.
We store and use binaries of necessary versions in `~/.docksal/bin`. Other then `fin` nothing else would see or use those binaries.

>I'd like to use and contribute to this repo
We do need more testing done with Docker for Mac. If this is something you'd be interested in and can contribute back - that would be great.

**Comment by mccrodp** [comment]
All great info, many thanks for the detailed response, especially `export DOCKER_NATIVE=1`. I'm currently testing some of the repos in https://github.com/4AllDigital and then will get back to this ASAP. Will keep you posted. Thanks!

**Comment by geerlingguy** [comment]
> Docker for Mac with osxfs is still very slow. Slower than VirtualBox with vboxsf.

@lmakarov - Could you put together a test run that could be scripted and posted to https://github.com/docker/for-mac/issues/77, so the Docker/Mac team could use it when they're working on priority for osxfs performance improvements.

IMO, that's the #1 reason many people (like me) are still holding back from Docker usage on Mac—the only way to run things like Drupal with anything resembling performance is to throw in the whole docker-machine/VirtualBox widget on top, which makes it no more appealing than a Vagrant-based solution (and masks some additional complexity).

**Comment by derimagia** [comment]
For people seeing this now, it looks like other "mounts" were added into docksal - including unison via cweagans/bg-sync. It's my personal favorite solution since it requires nothing to run on the host and uses osxfs but it's a lot faster since it syncs in the background using unison.

https://github.com/docksal/docksal/blob/ea230c50743a970c3432cffaf65e5fc53fc5e420/stacks/volumes-unison.yml

**Comment by lmakarov** [comment]
@derimagia You found an experimental feature (osx+unison sync) and get a point for that :)

We still have to do more testing and document it.
It's not going to be ideal in every situation though, as it (as well as others, e.g. nfs sync) have pros and cons. Unfortunately there is no silver bullet with any VM based solution (unless you are on Linux, where you do not need a VM at all to run containers). It really depends on the needs and priorities for each project.

`volumes-nfs.yml`

    # Mount project volumes with NFS
    # For use on Mac with VirtualBox or Docker for Mac
    # Pros: very good performance, almost realtime file sync 
    # Cons: no inotify/fs watchers

`volumes-unison.yml` (osx-unison)

    # Sync project volumes with Unison
    # For use with Docker for Mac osxfs.
    # Pros: native fs performance, fast file sync, inotify/fs watchers support.
    # Cons: 2x space usage (a mirror of the code base is maintained in a Docker volume), initial sync delay

**Comment by lmakarov** [comment]
@geerlingguy 
>Could you put together a test run that could be scripted

Yes, I was also thinking about that.

As was mentioned above, Docksal has experimental Docker volumes based support for `nfs` and `osxfs+unison` when used with Docker for Mac. This may become our recommended approach for Mac users, as Docker for Mac becomes more stable.

> ... no more appealing than a Vagrant-based solution ...

In it's base concept Docker for Mac/Windows is not very different from any other VM base approach for dev environments.
Everyone calls it "native" support for Docker on Mac/Windows, but looks like very few realize, that there is still a VM behind the scenes. It's just well hidden. Docker did a very good job here and made the UX very nice and smooth. You really have no idea about the VM and only interact with the native app. Your ports and volumes are mounted as if you were running Linux on your host. It's quite impressive.

Unfortunately, the code base sync problem (from host to VM) stays the same and there is not yet a good solution to that. It's a draw in this area. At least until Docker makes osxfs at least as performance as nfs.

In all other aspects Vagrant vs container approach is very different. With containers you get:

- **micro-service architecture** - HUGE flexibility and efficiency, you are no longer stuck with a single stack configuration and can switch things over or have multiple absolutely different stacks running in isolation side by side on a single host
- **no provisioning**, since images are pre-compiled and are delivered very efficiently thanks to layers - saves time and is a lot more reliable, than rebuilding a VM every time, or distributing a several GBs monster base image for Vagrant
- **no need in a VM on Linux** (I know your point was specifically Mac, but we should not forget cross-platform compatibility) - you get same level of isolation as with a VM, but without the whole overhead of a VM (getting native performance)

Those are the frontliners of the container (r)evolution.

**Comment by derimagia** [comment]
@lmakarov nfs is definitely fast in comparison to osxfs and virtualbox shared folders, but I'd argue another con is that it's slow for sites like Drupal 8 in comparison to Native speed, but I agree with all your points.

I will probably be trying out this more in the next few days. A lot of what I did initially was looking at the source code and how it works (Looked at what files it makes, the Dockerfile, etc). I have looked at a bunch of different methods and although there are some things that I will be looking to improve, its does everything closest to what I think is the best way. 

I'd say the main thing that I'm envisioning is some type of api tool that does what this is doing but nothing to specific in anything (No web specific, not drupal/wordpress specific, etc) and it only has a concept of things like global services (can stop/start all of them, customize them, etc) and application (with it's own containers/services) and then application templates of some kind - all  trying to use the docker-compose format like you guys do. Then you'd have another project that adds the specifics. Right now if I wanted to change the global services it's not doable without forking especially since it's all one file. But, I'm rambling. Great work on what you've done so far!

**Comment by lmakarov** [comment]
@derimagia 
> Right now if I wanted to change the global services it's not doable without forking especially since it's all one file

You are in no way limited to the global (default) services defined in https://github.com/docksal/docksal/blob/develop/stacks/services.yml

Those are used as a quick start (we call it "no config" option internally) and you are free to define the stack the way you want per project in `.docksal/docksal.yml` in the project's code base.

Take a look at our sample project repos for D7, D8 and WP.
- https://github.com/docksal/drupal7
- https://github.com/docksal/drupal8
- https://github.com/docksal/wordpress

They have a lot in common, but do not extend from the default services library.

You can mix and match as you want. Extend some services from the global library, while others are defined at the project level or have a completely custom setup for you project.

**Comment by derimagia** [comment]
Think you're thinking I meant project services when I say global services? Not sure, but for global services you hardcode them: https://github.com/docksal/docksal/blob/ed7e38a5333a0a6f1a4b67d107d45cd440fa59fa/bin/fin#L1748

**Comment by lmakarov** [comment]
Ah, right. The system service are indeed hardcoded, since Docksal and Docksal powered projects rely on them.

**Comment by achekulaev** [comment]
> No web specific
I don't think Docksal will ever go non-web-specific way.

**Comment by derimagia** [comment]
Was never saying it should and if you had to compare it to an existing tool docker-compose isn't a good comparison. docker-stack probably would be closest.
