### ISSUE TITLE
Dealing with Kerberos instead of SSH public key

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#287]
I'm working with a government client that wants to make the move to a Docksal-based local development strategy, which is excellent. However, they use Kerberos for access to internal infrastructure rather than your classic SSH publickey authentication strategy.

Do you have any recommendations for getting Kerberos integrated with Docksal? I imagine modifications might have to be made to the ssh-agent and cli services.

**Comment by lmakarov** [comment]
@lpeabody I have no idea how Kerberos works and what's involved. Are you able to share more details?

**Comment by achekulaev** [comment]
@lmakarov found this http://www.roguelynn.com/words/explain-like-im-5-kerberos/

**Comment by lpeabody** [comment]
So I've arrived at an interim solution which I believe will likely solve 90% of cases needing Kerberos-enabled SSH via GSSAPI. Basically, install krb5-config, krb5-user and libgssapi-krb5-2, and at installation specify your default realm. This will generate /etc/krb5.conf, and you just need to copy that into a Docker build project, which currently has a Dockerfile and a copy of krb5.conf.

```
FROM docksal/cli

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes --no-install-recommends install \
    krb5-config \
    krb5-user \
    libgssapi-krb5-2 \
    # Cleanup
    && DEBIAN_FRONTEND=noninteractive apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY krb5.conf /etc/krb5.conf
```

This works well for me. I'm not sure where a good place is to store all this extra info that some people might find useful. I guess this issue queue is good enough for now?

**Comment by achekulaev** [comment]
@lpeabody it's perfect. Thanks for contributing back your solution it looks clean and straightforward!

**Comment by lmakarov** [comment]
@lpeabody 

> Kerberos-enabled SSH via GSSAPI

You in your case you **are** actually using SSH to connect, but instead of an SSH key loaded in the agent (docksal-ssh-agent service) you use... what?

It's cool that the solution is that simple, I just wanted to make sure I understand the whole setup better to see, if that is something we'd want to officially support.

**Comment by lpeabody** [comment]
@lmakarov It uses GSSAPI for authentication as an alternative to publickey.

https://www.slac.stanford.edu/comp/unix/sshGSSAPI.html
https://en.wikipedia.org/wiki/Generic_Security_Services_Application_Program_Interface

**Comment by thomscode** [comment]
@lmakarov,

You are correct; installing the `krb5` package in the container adds the appropriate commands to allow the container to talk to the Kerberos server (using the `kinit` and similar commands). 

Then setting the GSSAPI settings in the ssh `config` file tells SSH to see if the SSH server you are trying to connect to will accept your Kerberos ticket for authentication. 

In our system (I'm the government client @lpeabody is working with) each of our computers gets a Kerberos ticket when it authenticates with the network server on user login. So this allows secure pre-authenticated login without passwords.

In the case of Docksal, this allows us to use Drush to authenticate with our production server from inside the Docksal containers to do database and file syncing (and any other `drush` operations we need to perform on the production machine) and not have to worry about synchronizing key files.

I hope that explains the use case a little bit and helps your understanding.

For our use case we are hosting our own Docker repository locally, and just need to setup the CI mechanism to detect when the appropriate Docksal images update. This way each person using our modified image doesn't need to build the custom image each time. I can see the custom `Dockerfile` being very useful in cases where a specific project needs something custom and look forward to seeing the documentation on that.

**Comment by lmakarov** [comment]
@thomscode ,

> In our system (I'm the government client @lpeabody is working with) each of our computers gets a Kerberos ticket when it authenticates with the network server on user login. So this allows secure pre-authenticated login without passwords.

OK, so you do authenticate on the network with a login/password, but then receive a kerberos ticket that can be used else where without further login/password prompts. Can I call this "single-sign-on" in modern terms? :)

What's still not cleat to me is - with the Kerberos ticket available somewhere on the host (since the host did the initial authentication on the network), how is that made available to a container?

In Docksal using SSH keys, `fin` pushes the SSH keys from the host to the `docksal-ssh-agent` service (using `docker cp`), where they are loaded into ssh-agent (in-memory) and are not stored at rest.

Do you have to authenticate with Kerberos again inside the `cli` container, then the received ticket can be used to further authenticate with other services within the Kerberos realm?

> I can see the custom Dockerfile being very useful in cases where a specific project needs something custom and look forward to seeing the documentation on that.

Look no further :) This was implemented in [v1.4.0](https://github.com/docksal/docksal/releases/tag/v1.4.0) and is documented [here](http://docs.docksal.io/en/v1.4.0/advanced/extend-images/)

**Comment by lpeabody** [comment]
@lmakarov 

> Do you have to authenticate with Kerberos again inside the cli container, then the received ticket can be used to further authenticate with other services within the Kerberos realm?

This is what we're currently doing. It was the most straight-forward approach and it worked so I didn't investigate further regarding rolling this functionality into the ssh-agent service.

**Comment by thomscode** [comment]
@lmakarov,
Thanks for pointing out the documentation. I'll check it out for future reference.

Regarding the Kerberos, yes, this would be considered a Single-Sign-On. On Windows and macOS I'm not aware of a way to pass the Kerberos ticket to the container, since docker (whether using `docker-machine` or Docker Native) uses virtualization to run a linux host where the containers are run. In a Linux environment, I assume the kerberos ticket would automatically pass from the host to the container, but I don't know that is the case and am not sure if @lpeabody has tried that or not.

I'm only familiar enough with both Docker and Kerberos to keep myself out of too much trouble. :)

Right now @lpeabody's solution works for us, however if you can find a way to use the Kerberos ticket from the host machine, we would be very interested in learning more about it.

**Comment by lpeabody** [comment]
@thomscode and @lmakarov I remember coming across a potential solution for the host sharing tickets with containers. Let me preface this by also saying this is a learning experience for me and I might say something incorrect. Reference material first:

- https://www.projectatomic.io/blog/2014/09/yet-another-reason-containers-don-t-contain-kernel-keyrings/
- https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
- https://web.mit.edu/kerberos/krb5-1.12/doc/basic/ccache_def.html

> Secure computing mode (seccomp) is a Linux kernel feature. You can use it to restrict the actions available within the container. The seccomp() system call operates on the seccomp state of the calling process. You can use this feature to restrict your application’s access.

> This feature is available only if Docker has been built with seccomp and the kernel is configured with CONFIG_SECCOMP enabled. To check if your kernel supports seccomp:

So, essentialy, the Kerberos cache can be stored in a variety of ways (file, keyring, memory, dir). Specifically, file and keyring allow the potential for the host to share tickets with containers.

You could theoretically mount the file holding the cache in the containers, and tell Kerberos configuration to look at that file (I think you can do that).

Then there's the keyring, which I guess is part of the Linux kernel, and it is not namespaced so therefore containers should have access to it. However, an additional function of the kernel called seccomp can be setup to deny this from being shared. If the kernel is compiled with support for seccomp, and Docker is as well, then you can configure Docker to instruct it's containers to access the keyring.

Both could bare some investigation.

**Comment by lmakarov** [comment]
> Right now @lpeabody's solution works for us, however if you can find a way to use the Kerberos ticket from the host machine, we would be very interested in learning more about it.

We do not have clients using Kerberos for SSO, so I don't really have a use case for this nor a testing ground.

I did more googling on the topic and found the following articles to be useful in further understand of the authentication and ticket storage process with Kerberos:

https://docstore.mik.ua/orelly/networking_2ndEd/ssh/ch11_04.htm
https://community.cloudera.com/t5/Hadoop-101-Training-Quickstart/Understanding-Kerberos-ticket-forwarding-and-SSO/ta-p/28805

If Kerberos ticket cache on the host is stored in a predictable location (e.g. `/tmp/krb5cc_1000`) then it might be possible to mount that into a container. I have no idea whether Kerberos will tolerate this kind of ticket cache highjacking though.

Looks like for now logging in and getting a Kerberos ticket inside `cli` should be good enough.

Ideally I'd see this done in a service container and then Kerberos tickets made available to other containers via a volume mount (similar how this is done with `docksal-ssh-agent`).

**Comment by lmakarov** [comment]
@lpeabody, @thomscode I'm going to close this ticket for now as within the Docksal/FFW teams we do not have a use cases for this and thus cannot document/support it going forward.
There was enough detail provided in this issues to help others with Kerberos authentication in a Docksal environment.

If either of you would be willing to write a guest post on the topic in Docksal's official blog (https://blog.docksal.io) on Medium, let me know :)

**Comment by sarbazx** [comment]
> FROM docksal/cli

> RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes --no-install-recommends install \
    krb5-config \
    krb5-user \
    libgssapi-krb5-2 \
    # Cleanup
    && DEBIAN_FRONTEND=noninteractive apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

> COPY krb5.conf /etc/krb5.conf

Hi @lpeabody, I have used above configuration to extend cli container but can't start web container. Where did you write virtual host settings for apache to authenticate with kerberos?

I have written on ```.docksal/etc/apache/htttpd-vhosts.conf``` like this:

```
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
    DocumentRoot /var/www/web

    ServerName kerberos.docksal
    <Location /user/login/sso>
        AuthType Kerberos
        AuthName "Kerberos authenticated intranet"
        KrbAuthRealms KERBEROS.LOCAL
        Krb5Keytab /var/wwww/intranet.keytab
        KrbServiceName Any
        KrbMethodNegotiate on
        KrbMethodK5Passwd on
        KrbSaveCredentials on
        KrbVerifyKDC on
        Require valid-user
    </Location>

</VirtualHost>

```
but it is giving me error on web container.

<img width="1048" alt="CleanShot 2022-01-03 at 10 20 58@2x" src="https://user-images.githubusercontent.com/5629946/147907056-d737b25c-0775-498a-a748-15c028e62223.png">

What should I do? should I extend web container instead of cli?
