### ISSUE TITLE
Investigate docker-sync option for syncing files

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#305]
Docker Sync. Seem to be optimized for docker-compose which is our use case http://docker-sync.io/

**Comment by lmakarov** [comment]
docker-sync is a ruby gem, so that adds to the dependency chain on the host - something we are trying to minimize and avoid with Docksal.

Under the hood docker-sync is doing either rsync or unison. We already have a POC for using Unison with Docker for Mac with 0 host dependencies involved (pending documentation: https://github.com/docksal/docksal/issues/119). I'm thinking about extending that to non-D4M use cases as well with a single dependency of the Unison binary on the host.

We may borrow some ideas from docker-sync, but I don't see us using it directly in Docksal as an out-of-the-box method.

**Comment by achekulaev** [comment]
It says it can work in native FS events mode but this dependency is kind of deal breaker for now

```
Windows 10 Pro 1703 (creators update) REQUIRED
```

**Comment by achekulaev** [comment]
> 0 host dependencies involved
Not even unison binary required? :)
