### ISSUE TITLE
Feature: Possibility to use exec_target for any service

### ISSUE THREAD

**Issue by b-connect** [docksal/docksal#356]
It would be a great enhancement to use exec_target in custom commands for all services declared in docksal.yml .

Example:

We have a docker image for sass/js compiling. It is not possible now (or i havent found a way) to execute a command in this container.

**Comment by achekulaev** [comment]
fin 1.35.0. Allows any exec_target for addons and custom commands.

Requires that container that serves as exec_targeet to have volume just like cli mapped to source
```
    volumes:
      # Project root volume
      - project_root:/var/www:rw,nocopy
```

**Comment by mkochendorfer** [comment]
@achekulaev 
Not sure if this is still working as expected in fin 1.80.1, but I am running into issues where the `PROJECT_ROOT` environment variable is not set inside of any of the containers except cli, and thus using exec_target of anything other than cli gives me errors like this:
```
fin test
bash: /.docksal/commands/test: No such file or directory
```

Because the file is actually at `/var/www/.docksal/commands/test` but since `PROJECT_ROOT` is not set in the container it ends up with a weird path.  I am able to work around this issue by setting the `PROJECT_ROOT` to the `/var/www` in `docksal.yml` environment vars, but that is both not documented anywhere and an odd extra step.  And extra info on something I may have missed would be appreciated.

**Comment by achekulaev** [comment]
@mkochendorfer there is no way to set `PROJECT_ROOT` in all containers. It is artificially hardcoded in `cli` for better scripts compatibility. For all other containers you can set `PROJECT_ROOT` as you did, or use `/var/www` instead, which is the same.

**Comment by mkochendorfer** [comment]
Good to know.  Thanks for the info.

**Comment by achekulaev** [comment]
Also theoretically we cannot know what PROJECT_ROOT is in custom containers. User can map it to any folder they want. Mapping it to a random folder will not really work for `cli` or `web`, or `db` so we could hardcode it for these containers, however. What container were you trying to execute the command in?

**Comment by mkochendorfer** [comment]
This is a node service.  I think just docs indicating the need to set this in docksal.yml if you want to run custom commands with an exec_target would be sufficient and more flexible.
