### ISSUE TITLE
Question: how can I make proper symlink to projectB inside projectA (docksal)?

### ISSUE THREAD

**Issue by ApacheEx** [docksal/docksal#364]
Let's imagine (I'm macOS user with virtualbox docker installation):

1. `~/WEB/projectA` - it's a docksal project (Basic LAMP stack for d7 which is accessible by http://projectA.docksal).
2. `~/WEB/projectB` - it's another project without docksal initialization (there is simple index.html file inside).
3. I made: `ln -s ~/WEB/projectB ~/WEB/projectA/docroot/projectB`

in the `~/docksal.env` I have:
```
DOCKSAL_NFS_PATH=~/WEB
```

in the `~/WEB/projectA/.docksal/docksal.env` I have:
```
DOCKSAL_STACK=default
WEB_IMAGE='docksal/web:2.1-apache2.4'
CLI_IMAGE='docksal/cli:1.3-php5'
DB_IMAGE='docksal/db:1.1-mysql-5.5'
MEMCACHED_IMAGE='memcached:1.4-alpine'
VIRTUAL_HOST=projectA.docksal
DOCROOT=docroot
XDEBUG_ENABLED=0
```

question: is there any possibility to access page http://projectA.docksal/projectB/index.html?

**Comment by lmakarov** [comment]
By default, stack containers do not have access to anything above the project root directory. For that reason, symlinking anything above the project root won't work.

What you are asking for can be achieved via an additional Docker volume, like this:

**docksal.yml**

```
version: "2.1"

services:
  cli:
    volumes:
      - ${PROJECT_ROOT}/../projectb:/var/www/docroot/projectb

```

`fin up` to update container configuration.

That would be the equivalent of `ln -s ~/WEB/projectB ~/WEB/projectA/docroot/projectB`.

Keep in mind, that volumes cannot go above `DOCKSAL_NFS_PATH`, since that's the top-most path on the host, where the Docksal VM will have access to.

> question: is there any possibility to access page http://projectA.docksal/projectB/index.html?

You the following volume mount: `${PROJECT_ROOT}/../projectb/docroot:/var/www/docroot/projectb`

**Comment by ApacheEx** [comment]
works like a charm, thank you!
