### ISSUE TITLE
Allow for private addon repo via ENV var

### ISSUE THREAD

**Issue by vml-bsummers** [docksal/docksal#368]
if URL_REPO_ADDONS could be configured in docksal.env then I would be able to host private addons available within my company.

**Comment by achekulaev** [comment]
Functionality added to the `develop` branch in the commit above.

The source repo is controlled not via the environment variable though, because I would like to keep experience of installing addons from the Docksal repo streamlined and with environment variable in could easily be disrupted.

However now you can install addons from a different repo by providing repo path in the addon install command. 

Example:
```
fin addon install achekulaev/docksal-addons/uli
```

Of course it requires the source repo (in this case https://github.com/achekulaev/docksal-addons/) to follow the same structure the https://github.com/docksal/addons repo is following. Addons can only be installed from the `master` branch at the moment.

**Comment by vml-bsummers** [comment]
Does this require the additional repo to be on github? 

What about just a secondary repo to check if not found in the primary add-on repo?

**Comment by achekulaev** [comment]
Yes it only supports Github at the moment. Other providers have very different URL structures. Which one you are interested in?

> What about just a secondary repo to check if not found in the primary add-on repo?

I feel a security issue with such approach.

**Comment by vml-bsummers** [comment]
We use hosted bitbucket. But this is all just how I would want to use such a feature. I'm not really considering other uses or abuses

**Comment by achekulaev** [comment]
I guess hosted bitbucket is going to be a popular option. I would create a separate ticket for that. It will require additional work. 
Currently addons are installed by pulling the files directly. fin does not clone the whole repo just to install a single addon. That's why it is dependent on the URLs structure of the repo cloud provider.
So for GitHub it's one:
`https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/$PATH/$FILE`
While for BitBucket it is different 
https://bitbucket.org/$USER/$REPO/raw/$COMMIT_HASH/$PATH/$FILE
and I guess hosted BitBucket it is yet different from that and I don't even have the latter at the moment to test.

**Comment by lmakarov** [comment]
@achekulaev 8887096 expands the scope of where an addon can be pulled from on Github, but it still has to sit a **public** repo.

I believe this issue is about supporting **arbitrary** and/or **private** git repos.

That can be achieved if either: 

- every addon sits in it's own repo (like custom Drupal modules or any other library over there). I'm not a fan of this idea.
- the while "addons" repo is pulled with git every time to get only a specific addon from it. While it sounds inefficient, I don't this this would be such a bad idea.

**Comment by achekulaev** [comment]
Yes the only viable solution to implement a generic git repo is to pull the repo with git. I'm processing this though at the moment. 
Most likely I will end up with 2 logics: 
1. simple HTTP for Public ones (btw GitLab that also follows https://gitlab.com/$USER/$REPO/raw/$BRANCH/$FILE pattern) 
2. git checkout (implies ssh key?) for private repos

**Comment by shelane** [comment]
Related #405

**Comment by shelane** [comment]
> 2. git checkout (implies ssh key?) for private repos

I would expect this to be the case that users told to add an addon to their project from a private repo would have access to that repo and the onus would be on the person to know that.

I believe that is a reasonable expectation to have.

**Comment by shelane** [comment]
Succeeded by #405
