### ISSUE TITLE
Install on clean Ubuntu 16.04 leads to error

### ISSUE THREAD

**Issue by haixiang** [docksal/docksal#374]
**Description**
Got fresh installation of ubuntu 16.04 on AWS. Execution of `curl -fsSL get.docksal.io | sh` results into this error:
```
...
Enabling automatic *.docksal DNS resolver...
ssh-agent
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/info: dial unix /var/run/docker.sock: connect: permission denied
 ERROR:  Current user is not part of the docker group.
         Have you run newgrp docker after fin update?
Update finished
```

**Steps to reproduce the issue:**

1. Launch ubuntu instance (ami-10547475) on aws and ssh into it (user `ubuntu`).
2. run `curl -fsSL get.docksal.io | sh`
3. observe the error

Following the recommendation to run `newgrp docker` and re-running the install script resolves it.

**Comment by achekulaev** [comment]
It is an expected behavior. Upon Docker installation your current user is being added to the `docker` group which has access to the Docker daemon, however Linux works in the way that user needs to re-login for this to take effect. `newgrp docker` is a workaround proposed by Docker to run current terminal session with this new setting without performing re-login. It is a temporary measure, please relogin/reboot workstation when possible to finish the group application.
