### ISSUE TITLE
macOS High Sierra critical issue(s) with NFS + APFS

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#377]
Creating this for visibility.
Not much we can do at this point as the issues was introduced upstream all they way to macOS

Going to reference issues from other communities here. Hopefully someone will discover a decent workaround which we can port to Docksal.

- [Do not update to macOS High Sierra if you use Docksal or Vagrant](https://blog.docksal.io/do-not-update-to-macos-high-sierra-if-you-use-docksal-or-vagrant-3ea461805169) - our blog post
- [NFS folders not properly synced on macOS High Sierra](https://github.com/hashicorp/vagrant/issues/8788) - same issue discussed in Vagrant community
- [NFS permission problem on MacOS Sierra](https://github.com/hashicorp/vagrant/issues/8061)

**Comment by ApacheEx** [comment]
I can confirm that it works well with
![image](https://user-images.githubusercontent.com/1918108/32554289-fa913616-c4a1-11e7-9169-19b0abf0acf8.png)

on MacOS 10.13.1 it still doesn't work.

**Comment by MKorostoff** [comment]
Hey all, having a look at https://github.com/hashicorp/vagrant/issues/8061#issuecomment-346131258 I think this is fixed in OSX High Sierra Beta 3

**Comment by MKorostoff** [comment]
oh, nvm, the previous comment already said that

**Comment by achekulaev** [comment]
Yeah we are waiting for the fix to be confirmed in stable release.

**Comment by ApacheEx** [comment]
Finally, 10.13.2 is released. 
https://support.apple.com/en-us/HT208179

**Comment by lmakarov** [comment]
> **About the macOS High Sierra 10.13.2 Update**
> This update is recommended for all macOS High Sierra users.
> 
> The macOS High Sierra 10.13.2 Update improves the security, stability, and compatibility of your Mac, and is recommended for all users.
>
> This update:
> - Improves compatibility with certain third-party USB audio devices.
> - Improves VoiceOver navigation when viewing PDF documents in Preview.
> - Improves compatibility of Braille displays with Mail.
>
> Enterprise content:
> - Improves performance when using credentials stored in the keychain to access SharePoint websites that use NTLM authentication.
> - Resolves an issue that prevented the Mac App Store and other processes invoked by Launch Daemons from working on networks that use proxy information defined in a PAC file.
> - If you change your Active Directory user password outside of Users & Groups preferences, the new password can now be used to unlock your FileVault volume (previously, only the old password would unlock the volume).
> - Improves compatibility with SMB home directories when the share point contains a dollar sign in its name.

They mentioned fixes for SMB home directories, but nothing about the NFS mixup :trollface: 

Can we get some reports from those who installed this update through the standard update mechanism (not the developer program)? All good?

**Comment by achekulaev** [comment]
Like it was not enough, there are more surprises from MacOS High Sierra. 10.13.2 includes a new security mechanism [User-Approved Kernel Extension Loading](https://developer.apple.com/library/content/technotes/tn2459/_index.html), that blocks VirtualBox System Extension (kernel extensions) from loading right away and requests a user action for that. 

VirtualBox does not know how to gracefully handle the reject to load it's kernel extension and thinks it is an error.

<img width="1024" alt="macos 10 13 2017-12-07 08-22-27" src="https://user-images.githubusercontent.com/402007/33718108-5232dbb0-db2a-11e7-943e-5b3b82bb6ccc.png">

<img width="1024" alt="macos 10 13 2017-12-07 08-23-16" src="https://user-images.githubusercontent.com/402007/33718112-56a08f76-db2a-11e7-9a22-9b2253cbabef.png">

<img width="1024" alt="macos 10 13 2017-12-07 08-23-47" src="https://user-images.githubusercontent.com/402007/33718123-5df5ee24-db2a-11e7-91dd-526c9d888a70.png">

Because of that VirtualBox does not install in one pass. 

If you try do `fin vm start` it will fail.

<img width="1024" alt="macos 10 13 2017-12-07 08-25-06" src="https://user-images.githubusercontent.com/402007/33718140-6db1f4de-db2a-11e7-8de2-d070eb5f4b8a.png">

Users needs to **RESTART THE WORKSTATION** after VirtualBox installation for kernel extension to enable.

![facepalm](https://user-images.githubusercontent.com/402007/33718182-89f2df00-db2a-11e7-8e35-6e97812bf7a5.jpg)

It is like Windows developers bite macOS developers and turned them into Windows developers...

Other than that it seems to be working fine. At least the example project installation has succeeded.

<img width="1024" alt="macos 10 13 2017-12-07 09-08-16" src="https://user-images.githubusercontent.com/402007/33719435-aef9e718-db2e-11e7-8e3b-95ac6e56ef8b.png">

In Vagrant related issue people report that NFS sync issue is fixed for them too in 10.13.2: https://github.com/hashicorp/vagrant/issues/8788#issuecomment-349915269
And apparently the old permissions over NFS issue might have been fixed in 10.13.1: https://github.com/hashicorp/vagrant/issues/8061#issuecomment-348345615

So yeah. Cheers!

**Comment by lmakarov** [comment]
@achekulaev thanks for confirming the NFS issues are not resolved with 10.13.2 and the details on the new KEXTs issue. I created a separate ticket for the KEXTs issue - https://github.com/docksal/docksal/issues/417

Closing this one.

**Comment by achekulaev** [comment]
Updated https://blog.docksal.io/do-not-update-to-macos-high-sierra-if-you-use-docksal-or-vagrant-3ea461805169
