### ISSUE TITLE
fin always rebuilds my images

### ISSUE THREAD

**Issue by JensvdHeydt** [docksal/docksal#448]
The documentation states that you can configure "image" and "build" in docksal.yml. My problem is that the "fin up" command constantly rebuilds my images instead of using a previously build one.

Example docksal.yml file in my project root:

version: "2.1"
services:
  web:
    hostname: web
    image: ${COMPOSE_PROJECT_NAME_SAFE}_web
    build: ${PROJECT_ROOT}/.docksal/services/web
    ...

Dockerfile:
FROM nginx:stable

The expected behaviour would be to have docksal reuse the previously created image. Instead it always rebuilds it. Am I missing something or this the intended behaviour?

The only workaround that is actually working for me is:
1. Build the containers
2. remove the build attribute in docksal.yml file

**Comment by lmakarov** [comment]
We do have to trigger `docker-compose build` every time, since just doing `docker-compose up` won't rebuild an image if there were changes in the associated Dockerfile/etc.

The overhead is minimal, however. Docker reuses cached layers and nothing is actually built if there were no changes in the image configs.

**Comment by achekulaev** [comment]
While seeing image being rebuilt every time might looks like an issue, it really isn't.

1. There is no way for Docksal to know if your built image is the latest. Even if we checked for `Dockerfile` changes that would not be enough, because `Dockerfile` can use some other files that can change. Therefore the best Docksal option is to run `docker-compose build` every time.

2. `docker-compose build` launches `docker` which knows what files changed and can compare things. If `docker` sees no changes then it does not **actually** rebuild image. You see output in the console, but there are no real changes made to images. That output is basically just a check if nothing has changed.

**Comment by JensvdHeydt** [comment]
This is a great explanation. Thank you very much! I'm still learning to use docker and docksal and my main concern was that I was actually doing something wrong here. Maybe we could address this issue with a little more explanation in the documentation?

**Comment by achekulaev** [comment]
Added to documentation
