### ISSUE TITLE
Add DOCKSAL_VOLUMES option to perform initial copy only

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#570]
We need to add a DOCKSAL_VOLUMES option (like "copy") that would only perform `docker cp` during the `cli` creation and not do any other mapping whatsoever after that.

**Comment by lmakarov** [comment]
@achekulaev can you please elaborate on the use case here?

**Comment by achekulaev** [comment]
Volume detached from the netowkr file system mount will provide maximum filesystem performance. So the option might be useful for performance maniacs, running project on sandbox server etc.

It can even be used on local. If [Cloud9 integration](https://github.com/docksal/docksal/issues/568) is enabled, then developer can actually productively edit code in that detached project via that IDE and commit it, all that while enjoying maximum performance.

**Comment by hanoii** [comment]
is cloud9 easy to run locally? I wonder if at this point, rather than a `DOCKSAL_VOLUMES=copy` you should just go all the way within the container, something in the like of 

`fin clone GITREPO`.

This could maybe just pull the `.docksal` on whatever is needed locally, run `fin init` with would then clone everything and do its thing.

Bear with me, I am just a newbie when it comes to docksal, just thinking out loud.

I am worried about other things here, like xdebug debugging, which I assume it's still possible and all that.

**Comment by hanoii** [comment]
handling branches with different .docksal environments might be an issue too, although I am not sure how's that currently being handled

**Comment by achekulaev** [comment]
@hanoii yes, cloud9 is easy to run locally https://blog.docksal.io/cloud9-ide-support-in-docksal-ed31abe43dbe

```bash
# In your project directory.
fin config set IDE_ENABLED=1
fin project reset cli
```

The use case you described makes sense. Start containers and then checkout the code inside. Don't even need to perform a copy. 

But to start the project `.docksal` is need and some automation that exists within it should be copied over into the container so it could be run there. So having DOCKSAL_VOLUMES=copy would still be needed to copy that `.docksal` folder into the container at least.

**Comment by achekulaev** [comment]
It is hard to know when is the proper time to perform copy as it should be performed only when container is created/recreated. And there is no way to know that beforehand. And there is no good way to catch `docker-compose up` output to find out too. 

I don't think this option is feasible.
