### ISSUE TITLE
Automatically switch to local DNS when Google DNS blocked

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#586]
A lot of people in corporate networks meet the DNS issue and it deters many newcomers from using Docksal.
It would be beneficial it we could automate the Upstream DNS switch.

On macOS and Linux current DNS server can be found in `/etc/resolv.conf`
On Windows it looks like Primary WINS Server might be the server we are looking for:

```bash
ipconfig /all | grep "Primary WINS"
```

We might also switch it back to `8.8.8.8` in case we detect that DOCKSAL UPSTREAM DNS is overridden but not accessible while `8.8.8.8` is accessible (person brought laptop home).

**Comment by achekulaev** [comment]
I actually going to change the direction of this ticket.

Why aren't we using the default user's DNS server to begin with?

**Comment by lmakarov** [comment]
> Why aren't we using the default user's DNS server to begin with?

In order to have `*.docksal` domains resolvable, we point user's DNS to `192.168.64.100` (`docksal-dns`). If we do not set the the upstream DNS server for `docksal-dns`, it ends up chasing its own tail (querying itself in an endless loop).

There might be a rule to prevent these kind of situations, but I was not able to find one that worked in `dnsmasq`.

**Comment by achekulaev** [comment]
Yeah that's what I thought. But looks like we've missed the point. 

1. On macOS and Linux we might be able to still detect DNS from /etc/resolv.conf
2. On Windows we can detect DNS *before* overriding user's DNS
3. `ipconfig /all | grep "Primary WINS"` might be the way to detect DNS regardless
