### ISSUE TITLE
Possible to extract complete docker-compose.yml file for building without Docksal in production?

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#665]
For people who want to use the same docker set up locally as in production, is docksal required for production deployments? Or can I extract a complete Docker compose file (generated from docksal config) so that I can just run Docker compose in other environments without needing to install docksal?

**Comment by achekulaev** [comment]
You can just take the output of fin config and it will run you your project containers just fine. 

But keep in mind that it is only project. It does not contain Docksal system services like dns, reverse proxy and ssh-agent. So you would have to organize that routing somehow. And since you have no fin you will have to handle your custom commands somehow yourself. 

So I'm not sure if there is any sense of doing so. If docker-compose would be enough, we would not be making Docskal 😃

**Comment by mikecrittenden** [comment]
Thank you!
