### ISSUE TITLE
Vhost URLs do not include docksal/vhost-proxy exposed ports

### ISSUE THREAD

**Issue by GMTA** [docksal/docksal#716]
**Description**
Changing the vhost-proxy ports through global configuration does not result in vhost URLs for applications that include said ports.

**Steps to reproduce the issue:**
1. Run `fin config set --global DOCKSAL_VHOST_PROXY_PORT_HTTP=8080`
2. Run `fin system reset`
3. Run `fin up` for a project

**Describe the results you received:**
Vhost URL is something like `http://project.docksal/`

**Describe the results you expected:**
Vhost URL is something like `http://project.docksal:8080/`

**Comment by GMTA** [comment]
The same issue arises with `DOCKSAL_VHOST_PROXY_PORT_HTTPS`. Since these are valid configuration items being used by `fin` to configure `docksal/vhost-proxy`, I would expect the URLs to include these ports.

**Comment by achekulaev** [comment]
Where exactly would you expect to see the port after the Virtual Host?

**Comment by GMTA** [comment]
@achekulaev Yeah, in `fin up`, `fin vhosts` and really all other places the URL might show up. It's confusing if you run another webserver on port 80/443 and you click a Docksal vhost URL only to find out it's something completely different.

**Comment by achekulaev** [comment]
@GMTA you see, virtual host **is** host. The name assumes that. It is basically this https://httpd.apache.org/docs/2.4/vhosts/ 
It's not host + port, that would be a url. 

The only built-in command I know that outputs URL is `fin up` and I can definitely throw in port there if it's not `80`.  However `vhosts` outputs virtual hosts. It has `http` at the beginning of them just for day-to-day use convenience. It is actually wrong to have http in vhosts output, but it is just convenient. Theoretically there should be no http there, because say `http://*.drupaltest.docksal` is not a valid URL.

Also I should say, that overriding default reverse proxy ports is a workaround rather than a recommended solution. We just left a way to do it for those marginal cases someone needs them. This is far from mainstream case.

**Comment by GMTA** [comment]
@achekulaev I'm not sure if I agree on your definition there, if you click through on your link to the examples page you can see that Apache's `<VirtualHost>` definitions actually can set a combination of `<IP>:<port>`.

So the host name of an application would be `<name>`. The virtual host in my opinion would be of the form `<name>[:<port>]` where the port is optional whenever the virtual host is used in an URL prefixed with either `http://` or `https://` and the port is equal to respectively 80 or 443. This distinction for a virtual host is important, because an application could have a completely different implementation for an HTTP-based application than for HTTPS, for example. Use case: redirect all traffic from HTTP to HTTPS using a simple virtual host-based redirection instead of error-prone `.htaccess` rules and checks.

Additionally, I think it's not an edge case since a lot of people will want to try out Docksal and in all likelihood will already have Apache or Nginx running on port 80/443. In my case, I want to run Docksal applications next to Kubernetes applications and this works fine - as long as you are able to move ports around.

Even if you do not want to support changing the ports as a recommended solution, I still think that whenever `fin` displays a URL for convenience it should at least display the correct one. A relatively simple fix would be to put URL generation in a function and use that in places where the URL is now displayed. But I'm open to all other opinions you might have on HTTP vs. HTTPS and customized ports in Docksal - if there's a direction you want to go in I can try to prepare a PR.

**Comment by lmakarov** [comment]
> whenever fin displays a URL for convenience it should at least display the correct one

I agree with @GMTA here.

There are two places in `fin` where URLs are printed:

- `fin up`
- `fin vhosts`

Both are trivial adjustment.

How do these look (see below)?

```
$fin up
...
drupal8_db_1 is up-to-date
drupal8_cli_1 is up-to-date
drupal8_web_1 is up-to-date
HTTP endpoint: http://drupal8.docksal:8080
HTTPS endpoint: https://drupal8.docksal:8443
```

```
$ fin vhosts
http://*.drupal8.docksal:8080
https://*.drupal8.docksal:8443
http://drupal8.docksal.*:8080
https://drupal8.docksal.*:8443
http://drupal8.docksal:8080
https://drupal8.docksal:8443
```

I'm not sure I like how `fin vhosts` looks. It also overlaps with `fin project list -a`:

```
$ fin pl
project             STATUS              virtual host                                          project root
drupal8             Up 8 hours          drupal8.docksal,*.drupal8.docksal,drupal8.docksal.*   /Users/leonid/Work/Labs/docksal/test/drupal8
```

Maybe `fin vhosts` should NOT print the protocol and the port and just list virtual hosts the same way `fin project list` does.

And one more thing. Users may choose to print the URL at the end of a custom command.
In that case, they would have to add the port suffix manually (if desired). E.g., instead of:

```
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
```

there would be this:

```
echo -e "Open ${yellow}http://${VIRTUAL_HOST}:${DOCKSAL_VHOST_PROXY_PORT_HTTP:-80}${NC} in your browser to verify the setup."
```

**Comment by achekulaev** [comment]
> in all likelihood will already have Apache or Nginx running on port 80/443.

You should reconfigure your apache or nginx to listen on `127.0.0.1` instead of `0.0.0.0` and it will not conflict with Docksal, they can both live on port `80` just fine. So many people are actually **not** expected to customize ports. 

> I still think that whenever fin displays a URL for convenience it should at least display the correct one

It makes sense, and that is why I am asking which cases specifically do you see. So far it is 
- `fin up`
- `fin vhosts`

Does that cover it?

**Comment by GMTA** [comment]
@achekulaev 
> You should reconfigure your apache or nginx to listen on 127.0.0.1
Things become more difficult if you run them in the same Docker for Mac instance. But I see your point!
> Does that cover it?
Searching through `fin`, there also is the `project create` which mentions project URLs at least twice. Additionally, I would love to have an environment variable like `PROJECT_URL` that I can use to display the URL people can click on after setting up a development environment, for example. Same use case as @lmakarov I believe.

**Comment by lmakarov** [comment]
I was also thinking about a variable like `PROJECT_URL`, bu which one would you use by default - HTTP or HTTPS? Or have both available as variables, I guess: `PROJECT_URL_HTTP`, `PROJECT_URL_HTTPS`.

**Comment by achekulaev** [comment]
Having `PROJECT_URL` variable(s) actually makes more sense to me in the light of this ticket.
