### ISSUE TITLE
Documentation update for xDebug

### ISSUE THREAD

**Issue by mike-potter** [docksal/docksal#734]
On the doc page: https://docksal.readthedocs.io/en/master/tools/xdebug/ there are 2 issues:

1) The screenshot for the "2) Set path mappings for the Drush binary in PHPStorm:" is broken.

2) It gives the following drush example:
```
For example you can run drush command: fin drush fra -y and debug this drush command from the Features module.
```
As the maintainer for the Features module, this is a very dangerous command example to give people.  Doing this on a site has a high chance of overriding any local config changes and breaking a site.  Should probably just use a simpler example such as ``fin drush status`` instead.  Or if you want to use a drush command example for debugging a module you can use ``fin drush fl`` to debug the ``features-list`` comment instead of the ``fra`` command (which is also good because the ``fl`` command works in both D7 and D8 whereas the ``fra`` command isn't recommended in D8)

**Comment by achekulaev** [comment]
Hi @mike-potter 

Thanks for the report. Images are already fixed in develop https://docksal.readthedocs.io/en/develop/tools/xdebug/ and will be released with the next stable release.

As for `fra -y` first of all I am very pleased to welcome maintainer of such an important module as features to the Docksal community and thanks for maintaining features module! 

We will review the line you pointed out. I have never actually seen a developer who uses features but does not know what feature revert does, but your comment makes sense to be on the safe side.
