### ISSUE TITLE
Add bdstart for Pattern Lab

### ISSUE THREAD

**Issue by amjad-wp** [docksal/docksal#824]
**Description**

Having to install bdstart for Pattern Lab to work.

**Steps to reproduce the issue:**

1. if you run `composer create-project pattern-lab/edition-drupal-standard FOLDERNAME`
2. Then choose the starterkit 
3. It fails with error `failed to extract the starterkit. easiest solution is to manually download it and copy <path>./dist</path to ./source/...`

**Describe the results you received:**
`failed to extract the starterkit. easiest solution is to manually download it and copy <path>./dist</path to ./source/...`

**Solution**
sudo apt-get update -y && sudo apt-get install bsdtar -y
Reference
https://github.com/fourkitchens/emulsify/issues/147#issuecomment-417483961

**Comment by achekulaev** [comment]
We would need more people to ask for it to add it to an image. At the moment bsdtar looks like a marginal utility needed for very narrow list of software. 
(And frankly speaking its pattern lab who should have relied on more widespread utilities rather than forcing users to install bsdtar to even try patternlab)

**Comment by amjad-wp** [comment]
@achekulaev You reckon I should just throw it to my local docksal.env as a post launch command ?

**Comment by achekulaev** [comment]
Yes, or add it to your custom `Dockerfile`, whichever you prefer.

**Comment by achekulaev** [comment]
Closing for now, unless it gets more upvotes.
