### ISSUE TITLE
Update Docksal to More Recent Version of Compose File format

### ISSUE THREAD

**Issue by mkochendorfer** [docksal/docksal#895]
Right now Docksal makes use of the Docker Compose 2.1 syntax for all of the .yml files.  However, Docker Compose has advanced all of the way to version 3.7 (https://docs.docker.com/compose/compose-file/).  These newer versions add support for various currently unsupported features.  For example, I am using a multi-stage build in my Dockerfile, and I would like to use a specific build target in the .yml file, but this field is not support until 2.3 (https://docs.docker.com/compose/compose-file/compose-file-v2/#target).

**Comment by mkochendorfer** [comment]
https://docs.docker.com/compose/compose-file/compose-versioning/ is a good resource on this topic

**Comment by achekulaev** [comment]
@mkochendorfer thanks for raising the issue. It is definitely something that needs to happen at some point of time, but please highlight which features exactly you would like to have? 

Postponing update the Compose version is intentional. Updating version in stack YMLs will make all configurations users had in their project incompatible, since all those have version 2.1 in them. So what will happen is users will update Docksal and their projects configurations will break until they change the version in `docksal.yml` and `docksal-local.yml`.

**Comment by shelane** [comment]
Related #701

**Comment by achekulaev** [comment]
Oh! Thanks Shelane. I am actually going to close this one in favor of that one. @mkochendorfer I would encourage you to provide arguments in favor of v3 in the #701

**Comment by mkochendorfer** [comment]
@achekulaev All of the features I need are available in the more recent 2.x versions.  2.3 specifically for the feature I mentioned above.  So we don't necessarily need to jump to 3.x, which probably would involve many more breaking changes.

**Comment by achekulaev** [comment]
@mkochendorfer changing version to any other is a breaking change. There is no difference what version to change to.

**Comment by achekulaev** [comment]
@mkochendorfer 

> Updating version in stack YMLs will make all configurations users had in their project level YMLs incompatible, since all those have version 2.1 in them. So what will happen is users will update Docksal and their projects configurations will break until they change the version in docksal.yml and docksal-local.yml.

This is breaking change for Docksal setups since user environments will be broken unless they take manual actions.

**Comment by achekulaev** [comment]
Not using stacks at all is not an option. Current;y it is not even technically possible, `fin` will try to include them always. But theoretically you could raise a feature request to prevent `fin` from loading any stack files at all. This could be an option (with lots of reservations of course), but it will never be the default option, and because of that it cannot serve as a solution to the breaking issue here. The whole idea of Docksal is to simplify things by providing unified approaches, while allowing customizations where sky is the limit.

**Comment by mkochendorfer** [comment]
Yep, makes sense.  I was worried that might be the case.  Always a challenge to build something that is both simple and easy to use while also being highly customizable and extensible by people with the right knowledge.  I will put in a feature request to capture this idea.  Thanks!
