### ISSUE TITLE
Document the fact that not all environment variables are accessible in all containers

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#896]
Related comment https://github.com/docksal/docksal/issues/356#issuecomment-446806345

Custom commands documentation needs to mention that not all environment variables are available if `exec_target` is not host or `cli`.

e.g. `PROJECT_ROOT` will not be set in other containers.

**Comment by mkochendorfer** [comment]
Updates to https://docs.docksal.io/fin/custom-commands/#executing-commands-inside-cli to indicate how to run custom commands with an `exec_target` other than `cli` would also be very useful because currently due to the `PROJECT_ROOT` not being set automatically in all containers custom commands will not even run in other containers without manually setting it in docksal.yml.

**Comment by shelane** [comment]
Custom commands can run in other containers without the environment variable set. The path is always /var/www and is defined as the project root (even without an environment variable) as defined by the volume. When needing to use the project root path as part of a custom command script, you will just need to declare `/var/www` instead of calling `${PROJECT_ROOT}`.

**Comment by mkochendorfer** [comment]
@shelane Unfortunately that is not the case.  Please review https://github.com/docksal/docksal/issues/356#issuecomment-446806345

Custom commands with an exec_target other than cli will not even execute unless you manually specify PROJECT_ROOT in docksal.yml.  https://github.com/docksal/docksal/blob/develop/bin/fin#L6174 is the line that causes it to fail.

**Comment by achekulaev** [comment]
@mkochendorfer oh ok that is completely different issue! This should be fixed in fin.
