### ISSUE TITLE
Can the installer provide some info about why root privileges are needed?

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#921]
```
$ curl -fsSL get.docksal.io | bash
Password:
```

^ That is fairly scary for lots of people, to just give a random script root access without any idea why it's needed or what it's doing. 

I understand that it's necessary in this case to be able to reliably install fin to usr/local/bin, but could the installer output a little helper text before the prompt that just says something like:

> Root privileges needed to move the fin command to /usr/local/bin, see here for more info: [link to docs]

**Comment by achekulaev** [comment]
@mikecrittenden this is funny because people seem to misunderstand that it is no different than `sudo apt-get install` when one also installs "random package" that contains random scripts that will be executed as root user or when one installs random software from the internet, launches it and it asks for administrative privileges in and GUI dialog window.

But this is a fair point that people might freak out and that we should add a message explaining why.

**Comment by achekulaev** [comment]
@lmakarov this one is pending for your thumbs up in PR
