### ISSUE TITLE
Database import broken

### ISSUE THREAD

**Issue by acondura** [docksal/docksal#932]
**Description**

I'm running 'fin init' and when it gets to the part where it says:

- 'fin db import db/*.sql.gz --progress'
- or 'fin db import db/*.sql'
- or 'fin sqli db/*.sql --force'

I always get the same error in the db container:

/entrypoint.sh: running /docker-entrypoint-initdb.d/staging-bmogamhub-com.sql.gz
Warning: Using a password on the command line interface can be insecure.
ERROR 1146 (42S02) at line 55608: Table 'default.browscap' doesn't exist

If I take out the database import part from my fin init, all runs fine and then if I run 'fin sqli db/*.sql --force' after fin init, everything imports fine. 

I've increased Docker for Mac to 5GB of RAM, swap to 3GB. Is there something I should add to my.cnf?
The database file is 279MB uncompressed, 29MB compressed.

I'm trying to initialize a project for a client so that the designer can familiarize himself with it. Any help would be appreciated!

**Comment by achekulaev** [comment]
1. db import only imports plain sql files
2. your error is SQL error. check sql in your sql dump

```
ERROR 1146 (42S02) at line 55608: Table 'default.browscap' doesn't exist
```

**Comment by acondura** [comment]
1. I have imported only plain sql files and I tried once the *.sql.gz file.

2. That does not explain why the standalone import command works after fin
init but it doesn't seem to be able to complete the same import command
from fin init.

**Comment by lmakarov** [comment]
I think, you have a mix of things in your setup.

The following does not come from `fin db import`

```
/entrypoint.sh: running /docker-entrypoint-initdb.d/staging-bmogamhub-com.sql.gz
Warning: Using a password on the command line interface can be insecure.
ERROR 1146 (42S02) at line 55608: Table 'default.browscap' doesn't exist
```

That is the built-in db initialization routine in the db container, which we inherit from the upstream `mysql` image. It does support `.sql`, `.gz` and `.sh` files mounted into `/docker-entrypoint-initdb.d/`.

You may be importing two different dumps. One mounted as `/docker-entrypoint-initdb.d/staging-bmogamhub-com.sql.gz`, which seems to be broken and causing issues. The other one uses `fin db import` (presumably with a different dump) and works fine.

Since you did not share the output from the diagnostic commands, the details of you stack configuration are unknown.

**Comment by lmakarov** [comment]
@acondura try removing the extra mount you have in the `db` service:

```
...
    volumes:
    - /Users/andreicondurachi/Sites/devdesktop/bmo2intra/db:/docker-entrypoint-initdb.d:ro
...
```

There is something wrong with the db dump you have in `/Users/andreicondurachi/Sites/devdesktop/bmo2intra/db/staging-bmogamhub-com.sql`, which breaks the init sequence of the `db` container. Are there any other meaningful log entries before this error in `fin logs db`?

```
ERROR 1146 (42S02) at line 334251: Table 'default.field_revision_field_file_audit_aef' doesn't exist
```

If you can import that dump with `fin db import` without issues, then just use that in your `fin init` command.

**Comment by acondura** [comment]
Thank you @lmakarov! Removing that volumes section above helped.
