### ISSUE TITLE
Feature request: Docksal version manager

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#934]
As I was working on the configuration for our Docksal CI server yesterday, I was struck by a thought: this server is setup to use a specific version of fin (the latest), however some projects were built and haven't been touched since fin version 1.69. Our init scripts generally make some use of core fin commands. Will these core commands never change? What if the way we're using them becomes deprecated? What about differing docker-compose versions between Docksal releases? What sort of backwards compatibility issues can arise when upgrading Docksal on a system?

In a perfect world, Docksal projects would be able to run against specific versions of Docksal. What is the feasibility of this? What complications would you foresee? Given my investment into Docksal-based CI, this is of great interest to me in terms of being able to rest easy without worrying about older projects breaking because I upgraded to the latest Docksal release. Food for thought!

**Comment by sean-e-dietrich** [comment]
@lpeabody yes you can prefix the install command to run specific versions of Docksal.

```
DOCKAL_VERSION=1.11.0 fin update
```

Where the version number corresponds with the release of docksal that was put out. Once you have done that you could lock docksal from performing updates. 

```
fin config set --global DOCKSAL_LOCK_UPDATES=1
```

So that updates cannot be ran accidentally. But to answer your question you cannot have projects run against specific versions of `fin` you can have them run against specific docker image versions which you would do by setting in `docksal.env` or `docksal.yml`.

**Comment by sean-e-dietrich** [comment]
The core commands can change but usually we will issue breaking notices of those changes before hand. If anything we have been implementing new commands or refactoring existing commands to make the more efficient but haven't been removing commands.

**Comment by achekulaev** [comment]
@lpeabody do you mean being able to install certain version of Docksal? Then it is possible as Sean has described above. But if you mean being able to install multiple different versions of Docksal, that would probably be challenging.

**Comment by lmakarov** [comment]
This sounds like "Docksal as the project level dependency" + "Fin Launcher", similar to how Drush 9 and Drupal Console have it now. Docksal is not designed to work that way.

As previously mentioned, you can always switch to a specific Docksal version locally. Though, I don't see this approach working well in CI, where you'd be running lots of projects concurrently. E.g., the underlying Docker version cannot really switch back and forth on-demand there.

When the time comes for some major changes in Docksal/fin internals, we will release a new major version. Otherwise, you can expect a fair amount of compatibility within minor Docksal versions, and hotfixes.

**Comment by lpeabody** [comment]
This ask is for installing multiple versions of Docksal in the same user environment. Thinking about a tool similar to RVM and NVM. The idea is that certain projects are built against specific versions of Docksal, and in a CI environment when that project builds it can be built against the same Docksal version every time.

I grant you that this will probably rarely come up, at least at this point in Docksal's evolution. From my perspective when I'm trying to build a CI environment that is running multiple Docksal projects, each of which was potentially developed against different versions of Docksal, all of a sudden running those projects on the latest version of Docksal in CI _could_ cause breaking changes down the line.

Thinking about an example of breaking changes down the line, let's say you update Docksal to use Docker Compose v3. If I installed that version of Docksal on CI, what would happen to the projects I have running on version 2.1? I guess that would be a major version bump anyway and it would be expected to have to expend effort to update your projects accordingly.

I'm just thinking about how to handle scenarios where Docksal projects no longer run due to updating to the latest version of Docksal on the CI environment. To @sean-e-dietrich's point about backwards compatibility between versions, that is super appreciated and puts me at ease a bit. Is your backwards compatibility policy documented?

**Comment by lpeabody** [comment]
Just reading @lmakarov's reply. I think the major version bump would be sufficient reasoning for me to either spin up another CI environment dedicated to the new major Docksal version and run two environments at once, if it is the case that backwards compatibility is maintained between minor versions.

Thanks for the feedback on backwards compatibility and mention of major version bump's breaking BC. I'm just going to copy/paste this whole discussion into the CI server maintenance document I'm working on... :) Gonna close this out.

**Comment by ozheller** [comment]
Thanks @sean-e-dietrich!

For those who are dense like me: 
DOCKAL_VERSION=1.11.0 fin update
Should be:
DOCKSAL_VERSION=v1.11.0 fin update
and the version should be the tag that's found in the releases https://github.com/docksal/docksal/releases
