### ISSUE TITLE
Docksal Support for Alpine Images

### ISSUE THREAD

**Issue by mkochendorfer** [docksal/docksal#942]
Right now fin seems to have a hard dependency on `bash` for many operations in the containers to function.  This means that when running containers (like Alpine based images) you will run into many different issues with various fin commands. `fin bash` and `fin exec` being the 2 most obvious commands.  There are work arounds for some of these things by falling back to docker-compose, but that limits the benefits of fin greatly. `fin dc run <container> /bin/ash` for example will get you to a shell in an Alpine based image.

`node:10.15.0-alpine` was the specific image I was testing with from https://hub.docker.com/_/node/ for reference.

**Comment by achekulaev** [comment]
Since there is no way to know which shell will be inside the container and using SH all the time is not an option, I can propose adding a feature, a parameter to `exec` - `--shell` giving ability to provide a shell binary

```
fin exec --in=mycontainer --shell=/bin/ash whatever
```

But I'm not sure if that will be convenient. This looks like a very long line. If I were in your shoes I would create a custom command to run `ash` or whatever you need in your custom containers.

`.docksal/commands/ash`

```bash
#!/bin/bash

## Runs ash shell with commands provided in <container>
##
## Usage: fin ash <command> [params]

fin dc run <container> /bin/ash "$@"
```

**Comment by achekulaev** [comment]
In the end what will happens is that `exec` will use `sh` by default so it will properly work for alpine images after the PR above is merged
